package com.novartis.ecrs.model.view.base;

import java.sql.Timestamp;

import oracle.jbo.RowSet;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun May 03 18:10:03 IST 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CrsContentBaseVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        CrsId {
            public Object get(CrsContentBaseVORowImpl obj) {
                return obj.getCrsId();
            }

            public void put(CrsContentBaseVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        CrsName {
            public Object get(CrsContentBaseVORowImpl obj) {
                return obj.getCrsName();
            }

            public void put(CrsContentBaseVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        StateId {
            public Object get(CrsContentBaseVORowImpl obj) {
                return obj.getStateId();
            }

            public void put(CrsContentBaseVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        CompoundId {
            public Object get(CrsContentBaseVORowImpl obj) {
                return obj.getCompoundId();
            }

            public void put(CrsContentBaseVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        GenericName {
            public Object get(CrsContentBaseVORowImpl obj) {
                return obj.getGenericName();
            }

            public void put(CrsContentBaseVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        TradeName {
            public Object get(CrsContentBaseVORowImpl obj) {
                return obj.getTradeName();
            }

            public void put(CrsContentBaseVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Indication {
            public Object get(CrsContentBaseVORowImpl obj) {
                return obj.getIndication();
            }

            public void put(CrsContentBaseVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IsMarketedFlag {
            public Object get(CrsContentBaseVORowImpl obj) {
                return obj.getIsMarketedFlag();
            }

            public void put(CrsContentBaseVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        ReleaseStatusFlag {
            public Object get(CrsContentBaseVORowImpl obj) {
                return obj.getReleaseStatusFlag();
            }

            public void put(CrsContentBaseVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        BslName {
            public Object get(CrsContentBaseVORowImpl obj) {
                return obj.getBslName();
            }

            public void put(CrsContentBaseVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Designee {
            public Object get(CrsContentBaseVORowImpl obj) {
                return obj.getDesignee();
            }

            public void put(CrsContentBaseVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        MqmComment {
            public Object get(CrsContentBaseVORowImpl obj) {
                return obj.getMqmComment();
            }

            public void put(CrsContentBaseVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        TaslName {
            public Object get(CrsContentBaseVORowImpl obj) {
                return obj.getTaslName();
            }

            public void put(CrsContentBaseVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        TaslRejectComment {
            public Object get(CrsContentBaseVORowImpl obj) {
                return obj.getTaslRejectComment();
            }

            public void put(CrsContentBaseVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        MedicalLeadName {
            public Object get(CrsContentBaseVORowImpl obj) {
                return obj.getMedicalLeadName();
            }

            public void put(CrsContentBaseVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        MedicalLeadRejectComment {
            public Object get(CrsContentBaseVORowImpl obj) {
                return obj.getMedicalLeadRejectComment();
            }

            public void put(CrsContentBaseVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        CrsEffectiveDt {
            public Object get(CrsContentBaseVORowImpl obj) {
                return obj.getCrsEffectiveDt();
            }

            public void put(CrsContentBaseVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        ReviewApproveRequiredFlag {
            public Object get(CrsContentBaseVORowImpl obj) {
                return obj.getReviewApproveRequiredFlag();
            }

            public void put(CrsContentBaseVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        UiVersionNumber {
            public Object get(CrsContentBaseVORowImpl obj) {
                return obj.getUiVersionNumber();
            }

            public void put(CrsContentBaseVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        CrsCompoundType {
            public Object get(CrsContentBaseVORowImpl obj) {
                return obj.getCrsCompoundType();
            }

            public void put(CrsContentBaseVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        CrsCompoundCode {
            public Object get(CrsContentBaseVORowImpl obj) {
                return obj.getCrsCompoundCode();
            }

            public void put(CrsContentBaseVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        StateName {
            public Object get(CrsContentBaseVORowImpl obj) {
                return obj.getStateName();
            }

            public void put(CrsContentBaseVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        DesigneeName {
            public Object get(CrsContentBaseVORowImpl obj) {
                return obj.getDesigneeName();
            }

            public void put(CrsContentBaseVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        CreationTs {
            public Object get(CrsContentBaseVORowImpl obj) {
                return obj.getCreationTs();
            }

            public void put(CrsContentBaseVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        ModificationTs {
            public Object get(CrsContentBaseVORowImpl obj) {
                return obj.getModificationTs();
            }

            public void put(CrsContentBaseVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        BSLUserVA {
            public Object get(CrsContentBaseVORowImpl obj) {
                return obj.getBSLUserVA();
            }

            public void put(CrsContentBaseVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        TASLUserVA {
            public Object get(CrsContentBaseVORowImpl obj) {
                return obj.getTASLUserVA();
            }

            public void put(CrsContentBaseVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        MLUserVA {
            public Object get(CrsContentBaseVORowImpl obj) {
                return obj.getMLUserVA();
            }

            public void put(CrsContentBaseVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(CrsContentBaseVORowImpl object);

        public abstract void put(CrsContentBaseVORowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int CRSID = AttributesEnum.CrsId.index();
    public static final int CRSNAME = AttributesEnum.CrsName.index();
    public static final int STATEID = AttributesEnum.StateId.index();
    public static final int COMPOUNDID = AttributesEnum.CompoundId.index();
    public static final int GENERICNAME = AttributesEnum.GenericName.index();
    public static final int TRADENAME = AttributesEnum.TradeName.index();
    public static final int INDICATION = AttributesEnum.Indication.index();
    public static final int ISMARKETEDFLAG = AttributesEnum.IsMarketedFlag.index();
    public static final int RELEASESTATUSFLAG = AttributesEnum.ReleaseStatusFlag.index();
    public static final int BSLNAME = AttributesEnum.BslName.index();
    public static final int DESIGNEE = AttributesEnum.Designee.index();
    public static final int MQMCOMMENT = AttributesEnum.MqmComment.index();
    public static final int TASLNAME = AttributesEnum.TaslName.index();
    public static final int TASLREJECTCOMMENT = AttributesEnum.TaslRejectComment.index();
    public static final int MEDICALLEADNAME = AttributesEnum.MedicalLeadName.index();
    public static final int MEDICALLEADREJECTCOMMENT = AttributesEnum.MedicalLeadRejectComment.index();
    public static final int CRSEFFECTIVEDT = AttributesEnum.CrsEffectiveDt.index();
    public static final int REVIEWAPPROVEREQUIREDFLAG = AttributesEnum.ReviewApproveRequiredFlag.index();
    public static final int UIVERSIONNUMBER = AttributesEnum.UiVersionNumber.index();
    public static final int CRSCOMPOUNDTYPE = AttributesEnum.CrsCompoundType.index();
    public static final int CRSCOMPOUNDCODE = AttributesEnum.CrsCompoundCode.index();
    public static final int STATENAME = AttributesEnum.StateName.index();
    public static final int DESIGNEENAME = AttributesEnum.DesigneeName.index();
    public static final int CREATIONTS = AttributesEnum.CreationTs.index();
    public static final int MODIFICATIONTS = AttributesEnum.ModificationTs.index();
    public static final int BSLUSERVA = AttributesEnum.BSLUserVA.index();
    public static final int TASLUSERVA = AttributesEnum.TASLUserVA.index();
    public static final int MLUSERVA = AttributesEnum.MLUserVA.index();

    /**
     * This is the default constructor (do not remove).
     */
    public CrsContentBaseVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute CrsId.
     * @return the CrsId
     */
    public Long getCrsId() {
        return (Long) getAttributeInternal(CRSID);
    }


    /**
     * Gets the attribute value for the calculated attribute CrsName.
     * @return the CrsName
     */
    public String getCrsName() {
        return (String) getAttributeInternal(CRSNAME);
    }


    /**
     * Gets the attribute value for the calculated attribute StateId.
     * @return the StateId
     */
    public Integer getStateId() {
        return (Integer) getAttributeInternal(STATEID);
    }


    /**
     * Gets the attribute value for the calculated attribute CompoundId.
     * @return the CompoundId
     */
    public Integer getCompoundId() {
        return (Integer) getAttributeInternal(COMPOUNDID);
    }


    /**
     * Gets the attribute value for the calculated attribute GenericName.
     * @return the GenericName
     */
    public String getGenericName() {
        return (String) getAttributeInternal(GENERICNAME);
    }


    /**
     * Gets the attribute value for the calculated attribute TradeName.
     * @return the TradeName
     */
    public String getTradeName() {
        return (String) getAttributeInternal(TRADENAME);
    }


    /**
     * Gets the attribute value for the calculated attribute Indication.
     * @return the Indication
     */
    public String getIndication() {
        return (String) getAttributeInternal(INDICATION);
    }


    /**
     * Gets the attribute value for the calculated attribute IsMarketedFlag.
     * @return the IsMarketedFlag
     */
    public String getIsMarketedFlag() {
        return (String) getAttributeInternal(ISMARKETEDFLAG);
    }


    /**
     * Gets the attribute value for the calculated attribute ReleaseStatusFlag.
     * @return the ReleaseStatusFlag
     */
    public String getReleaseStatusFlag() {
        return (String) getAttributeInternal(RELEASESTATUSFLAG);
    }


    /**
     * Gets the attribute value for the calculated attribute BslName.
     * @return the BslName
     */
    public String getBslName() {
        return (String) getAttributeInternal(BSLNAME);
    }


    /**
     * Gets the attribute value for the calculated attribute Designee.
     * @return the Designee
     */
    public String getDesignee() {
        return (String) getAttributeInternal(DESIGNEE);
    }


    /**
     * Gets the attribute value for the calculated attribute MqmComment.
     * @return the MqmComment
     */
    public String getMqmComment() {
        return (String) getAttributeInternal(MQMCOMMENT);
    }


    /**
     * Gets the attribute value for the calculated attribute TaslName.
     * @return the TaslName
     */
    public String getTaslName() {
        return (String) getAttributeInternal(TASLNAME);
    }


    /**
     * Gets the attribute value for the calculated attribute TaslRejectComment.
     * @return the TaslRejectComment
     */
    public String getTaslRejectComment() {
        return (String) getAttributeInternal(TASLREJECTCOMMENT);
    }


    /**
     * Gets the attribute value for the calculated attribute MedicalLeadName.
     * @return the MedicalLeadName
     */
    public String getMedicalLeadName() {
        return (String) getAttributeInternal(MEDICALLEADNAME);
    }


    /**
     * Gets the attribute value for the calculated attribute MedicalLeadRejectComment.
     * @return the MedicalLeadRejectComment
     */
    public String getMedicalLeadRejectComment() {
        return (String) getAttributeInternal(MEDICALLEADREJECTCOMMENT);
    }


    /**
     * Gets the attribute value for the calculated attribute CrsEffectiveDt.
     * @return the CrsEffectiveDt
     */
    public Timestamp getCrsEffectiveDt() {
        return (Timestamp) getAttributeInternal(CRSEFFECTIVEDT);
    }


    /**
     * Gets the attribute value for the calculated attribute ReviewApproveRequiredFlag.
     * @return the ReviewApproveRequiredFlag
     */
    public String getReviewApproveRequiredFlag() {
        return (String) getAttributeInternal(REVIEWAPPROVEREQUIREDFLAG);
    }


    /**
     * Gets the attribute value for the calculated attribute UiVersionNumber.
     * @return the UiVersionNumber
     */
    public Integer getUiVersionNumber() {
        return (Integer) getAttributeInternal(UIVERSIONNUMBER);
    }


    /**
     * Gets the attribute value for the calculated attribute CrsCompoundType.
     * @return the CrsCompoundType
     */
    public String getCrsCompoundType() {
        return (String) getAttributeInternal(CRSCOMPOUNDTYPE);
    }


    /**
     * Gets the attribute value for the calculated attribute CrsCompoundCode.
     * @return the CrsCompoundCode
     */
    public String getCrsCompoundCode() {
        return (String) getAttributeInternal(CRSCOMPOUNDCODE);
    }


    /**
     * Gets the attribute value for the calculated attribute StateName.
     * @return the StateName
     */
    public String getStateName() {
        return (String) getAttributeInternal(STATENAME);
    }


    /**
     * Gets the attribute value for the calculated attribute DesigneeName.
     * @return the DesigneeName
     */
    public String getDesigneeName() {
        return (String) getAttributeInternal(DESIGNEENAME);
    }


    /**
     * Gets the attribute value for the calculated attribute CreationTs.
     * @return the CreationTs
     */
    public Timestamp getCreationTs() {
        return (Timestamp) getAttributeInternal(CREATIONTS);
    }


    /**
     * Gets the attribute value for the calculated attribute ModificationTs.
     * @return the ModificationTs
     */
    public Timestamp getModificationTs() {
        return (Timestamp) getAttributeInternal(MODIFICATIONTS);
    }


    /**
     * Gets the view accessor <code>RowSet</code> BSLUserVA.
     */
    public RowSet getBSLUserVA() {
        return (RowSet)getAttributeInternal(BSLUSERVA);
    }

    /**
     * Gets the view accessor <code>RowSet</code> TASLUserVA.
     */
    public RowSet getTASLUserVA() {
        return (RowSet)getAttributeInternal(TASLUSERVA);
    }

    /**
     * Gets the view accessor <code>RowSet</code> MLUserVA.
     */
    public RowSet getMLUserVA() {
        return (RowSet)getAttributeInternal(MLUSERVA);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
