package com.novartis.ecrs.model.view.base;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Apr 17 23:50:43 IST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CrsContentBaseVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public CrsContentBaseVOImpl() {
    }

    /**
     * Returns the variable value for pCrsName.
     * @return variable value for pCrsName
     */
    public String getpCrsName() {
        return (String) ensureVariableManager().getVariableValue("pCrsName");
    }

    /**
     * Sets <code>value</code> for variable pCrsName.
     * @param value value to bind as pCrsName
     */
    public void setpCrsName(String value) {
        ensureVariableManager().setVariableValue("pCrsName", value);
    }
}

