package com.novartis.ecrs.model.lov;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jul 02 21:30:37 IST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ADRVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public ADRVOImpl() {
    }
}

