package com.novartis.ecrs.model.lov;

import java.math.BigDecimal;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jun 16 19:47:15 IST 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AgeSubGroupVVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        CrsAgeGrpId {
            protected Object get(AgeSubGroupVVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(AgeSubGroupVVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        CrsAgeSubGrpId {
            protected Object get(AgeSubGroupVVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(AgeSubGroupVVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        AgeCategory {
            protected Object get(AgeSubGroupVVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(AgeSubGroupVVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        AgeSubGrpCategory {
            protected Object get(AgeSubGroupVVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(AgeSubGroupVVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;


        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }


        protected abstract Object get(AgeSubGroupVVORowImpl object);

        protected abstract void put(AgeSubGroupVVORowImpl object, Object value);
    }


    public static final int CRSAGEGRPID = AttributesEnum.CrsAgeGrpId.index();
    public static final int CRSAGESUBGRPID = AttributesEnum.CrsAgeSubGrpId.index();
    public static final int AGECATEGORY = AttributesEnum.AgeCategory.index();
    public static final int AGESUBGRPCATEGORY = AttributesEnum.AgeSubGrpCategory.index();

    /**
     * This is the default constructor (do not remove).
     */
    public AgeSubGroupVVORowImpl() {
    }
}

