package com.novartis.ecrs.model.lov;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu May 14 03:20:38 IST 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DictionaryVVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public DictionaryVVOImpl() {
    }
}

