package com.novartis.ecrs.model.lov;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jun 16 19:26:04 IST 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class GenderVVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        GenderCode {
            protected Object get(GenderVVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(GenderVVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Gender {
            protected Object get(GenderVVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(GenderVVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;


        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }

        protected abstract Object get(GenderVVORowImpl object);

        protected abstract void put(GenderVVORowImpl object, Object value);
    }

    public static final int GENDERCODE = AttributesEnum.GenderCode.index();
    public static final int GENDER = AttributesEnum.Gender.index();

    /**
     * This is the default constructor (do not remove).
     */
    public GenderVVORowImpl() {
    }
}

