package com.novartis.ecrs.model.lov;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Oct 22 02:48:58 IST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class UserRoleVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public UserRoleVOImpl() {
    }

    /**
     * Returns the bind variable value for roleName.
     * @return bind variable value for roleName
     */
    public String getroleName() {
        return (String) getNamedWhereClauseParam("roleName");
    }

    /**
     * Sets <code>value</code> for bind variable roleName.
     * @param value value to bind as roleName
     */
    public void setroleName(String value) {
        setNamedWhereClauseParam("roleName", value);
    }
}

