package com.novartis.ecrs.model.view;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun May 10 15:51:59 IST 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AutolistednessVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public AutolistednessVOImpl() {
    }
}

