package com.novartis.ecrs.model.view;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Jun 02 17:06:05 IST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CrsBatchJobVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public CrsBatchJobVOImpl() {
    }
}

