package com.novartis.ecrs.model.view;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Aug 15 20:14:08 IST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CrsEarliestVersionRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        CrsId {
            protected Object get(CrsEarliestVersionRowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(CrsEarliestVersionRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EarliestSafetyTopic {
            protected Object get(CrsEarliestVersionRowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(CrsEarliestVersionRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EarliestSpp {
            protected Object get(CrsEarliestVersionRowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(CrsEarliestVersionRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EarliestSppColor {
            protected Object get(CrsEarliestVersionRowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(CrsEarliestVersionRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EarliestDsur {
            protected Object get(CrsEarliestVersionRowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(CrsEarliestVersionRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EarliestDsurColor {
            protected Object get(CrsEarliestVersionRowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(CrsEarliestVersionRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EarliestRmp {
            protected Object get(CrsEarliestVersionRowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(CrsEarliestVersionRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EarliestRmpColor {
            protected Object get(CrsEarliestVersionRowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(CrsEarliestVersionRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EarliestPsur {
            protected Object get(CrsEarliestVersionRowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(CrsEarliestVersionRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EarliestPsurColor {
            protected Object get(CrsEarliestVersionRowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(CrsEarliestVersionRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EarliestIb {
            protected Object get(CrsEarliestVersionRowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(CrsEarliestVersionRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EarliestIbColor {
            protected Object get(CrsEarliestVersionRowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(CrsEarliestVersionRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EarliestCds {
            protected Object get(CrsEarliestVersionRowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(CrsEarliestVersionRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EarliestCdsColor {
            protected Object get(CrsEarliestVersionRowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(CrsEarliestVersionRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EarliestOtherSearch {
            protected Object get(CrsEarliestVersionRowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(CrsEarliestVersionRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EarliestOtherSearchColor {
            protected Object get(CrsEarliestVersionRowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(CrsEarliestVersionRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EarliestMissingInformation {
            protected Object get(CrsEarliestVersionRowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(CrsEarliestVersionRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EarliestMissingInformColor {
            protected Object get(CrsEarliestVersionRowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(CrsEarliestVersionRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EarliestExpeditingRules {
            protected Object get(CrsEarliestVersionRowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(CrsEarliestVersionRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EarliestExpeditingRulColor {
            protected Object get(CrsEarliestVersionRowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(CrsEarliestVersionRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EarliestUnderlyingDisease {
            protected Object get(CrsEarliestVersionRowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(CrsEarliestVersionRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EarliestUnderlyingDisColor {
            protected Object get(CrsEarliestVersionRowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(CrsEarliestVersionRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EarliestAesiForNisProtcol {
            protected Object get(CrsEarliestVersionRowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(CrsEarliestVersionRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EarliestAesiFrNisProClr {
            protected Object get(CrsEarliestVersionRowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(CrsEarliestVersionRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EarliestAesiNotRmp {
            protected Object get(CrsEarliestVersionRowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(CrsEarliestVersionRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EarliestAesiNotRmpColor {
            protected Object get(CrsEarliestVersionRowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(CrsEarliestVersionRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EarliestSoc {
            protected Object get(CrsEarliestVersionRowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(CrsEarliestVersionRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EarliestSocColor {
            protected Object get(CrsEarliestVersionRowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(CrsEarliestVersionRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EarliestDataDomain {
            protected Object get(CrsEarliestVersionRowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(CrsEarliestVersionRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EarliestDataDomainColor {
            protected Object get(CrsEarliestVersionRowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(CrsEarliestVersionRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EarliestSearchDetails {
            protected Object get(CrsEarliestVersionRowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(CrsEarliestVersionRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EarliestSearchDetailsColor {
            protected Object get(CrsEarliestVersionRowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(CrsEarliestVersionRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EarliestMeddraCode {
            protected Object get(CrsEarliestVersionRowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(CrsEarliestVersionRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EarliestMeddraCodeColor {
            protected Object get(CrsEarliestVersionRowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(CrsEarliestVersionRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EarliestMeddraTerm {
            protected Object get(CrsEarliestVersionRowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(CrsEarliestVersionRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EarliestMeddraTermColor {
            protected Object get(CrsEarliestVersionRowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(CrsEarliestVersionRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EarliestMeddraExtension {
            protected Object get(CrsEarliestVersionRowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(CrsEarliestVersionRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EarliestMeddraExtColor {
            protected Object get(CrsEarliestVersionRowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(CrsEarliestVersionRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EarliestMeddraQualifier {
            protected Object get(CrsEarliestVersionRowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(CrsEarliestVersionRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EarliestMeddraQualColor {
            protected Object get(CrsEarliestVersionRowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(CrsEarliestVersionRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EarliestNonMeddraCompCmt {
            protected Object get(CrsEarliestVersionRowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(CrsEarliestVersionRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EarliestNonMedCompCmtClr {
            protected Object get(CrsEarliestVersionRowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(CrsEarliestVersionRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected abstract Object get(CrsEarliestVersionRowImpl object);

        protected abstract void put(CrsEarliestVersionRowImpl object, Object value);

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int CRSID = AttributesEnum.CrsId.index();
    public static final int EARLIESTSAFETYTOPIC = AttributesEnum.EarliestSafetyTopic.index();
    public static final int EARLIESTSPP = AttributesEnum.EarliestSpp.index();
    public static final int EARLIESTSPPCOLOR = AttributesEnum.EarliestSppColor.index();
    public static final int EARLIESTDSUR = AttributesEnum.EarliestDsur.index();
    public static final int EARLIESTDSURCOLOR = AttributesEnum.EarliestDsurColor.index();
    public static final int EARLIESTRMP = AttributesEnum.EarliestRmp.index();
    public static final int EARLIESTRMPCOLOR = AttributesEnum.EarliestRmpColor.index();
    public static final int EARLIESTPSUR = AttributesEnum.EarliestPsur.index();
    public static final int EARLIESTPSURCOLOR = AttributesEnum.EarliestPsurColor.index();
    public static final int EARLIESTIB = AttributesEnum.EarliestIb.index();
    public static final int EARLIESTIBCOLOR = AttributesEnum.EarliestIbColor.index();
    public static final int EARLIESTCDS = AttributesEnum.EarliestCds.index();
    public static final int EARLIESTCDSCOLOR = AttributesEnum.EarliestCdsColor.index();
    public static final int EARLIESTOTHERSEARCH = AttributesEnum.EarliestOtherSearch.index();
    public static final int EARLIESTOTHERSEARCHCOLOR = AttributesEnum.EarliestOtherSearchColor.index();
    public static final int EARLIESTMISSINGINFORMATION = AttributesEnum.EarliestMissingInformation.index();
    public static final int EARLIESTMISSINGINFORMCOLOR = AttributesEnum.EarliestMissingInformColor.index();
    public static final int EARLIESTEXPEDITINGRULES = AttributesEnum.EarliestExpeditingRules.index();
    public static final int EARLIESTEXPEDITINGRULCOLOR = AttributesEnum.EarliestExpeditingRulColor.index();
    public static final int EARLIESTUNDERLYINGDISEASE = AttributesEnum.EarliestUnderlyingDisease.index();
    public static final int EARLIESTUNDERLYINGDISCOLOR = AttributesEnum.EarliestUnderlyingDisColor.index();
    public static final int EARLIESTAESIFORNISPROTCOL = AttributesEnum.EarliestAesiForNisProtcol.index();
    public static final int EARLIESTAESIFRNISPROCLR = AttributesEnum.EarliestAesiFrNisProClr.index();
    public static final int EARLIESTAESINOTRMP = AttributesEnum.EarliestAesiNotRmp.index();
    public static final int EARLIESTAESINOTRMPCOLOR = AttributesEnum.EarliestAesiNotRmpColor.index();
    public static final int EARLIESTSOC = AttributesEnum.EarliestSoc.index();
    public static final int EARLIESTSOCCOLOR = AttributesEnum.EarliestSocColor.index();
    public static final int EARLIESTDATADOMAIN = AttributesEnum.EarliestDataDomain.index();
    public static final int EARLIESTDATADOMAINCOLOR = AttributesEnum.EarliestDataDomainColor.index();
    public static final int EARLIESTSEARCHDETAILS = AttributesEnum.EarliestSearchDetails.index();
    public static final int EARLIESTSEARCHDETAILSCOLOR = AttributesEnum.EarliestSearchDetailsColor.index();
    public static final int EARLIESTMEDDRACODE = AttributesEnum.EarliestMeddraCode.index();
    public static final int EARLIESTMEDDRACODECOLOR = AttributesEnum.EarliestMeddraCodeColor.index();
    public static final int EARLIESTMEDDRATERM = AttributesEnum.EarliestMeddraTerm.index();
    public static final int EARLIESTMEDDRATERMCOLOR = AttributesEnum.EarliestMeddraTermColor.index();
    public static final int EARLIESTMEDDRAEXTENSION = AttributesEnum.EarliestMeddraExtension.index();
    public static final int EARLIESTMEDDRAEXTCOLOR = AttributesEnum.EarliestMeddraExtColor.index();
    public static final int EARLIESTMEDDRAQUALIFIER = AttributesEnum.EarliestMeddraQualifier.index();
    public static final int EARLIESTMEDDRAQUALCOLOR = AttributesEnum.EarliestMeddraQualColor.index();
    public static final int EARLIESTNONMEDDRACOMPCMT = AttributesEnum.EarliestNonMeddraCompCmt.index();
    public static final int EARLIESTNONMEDCOMPCMTCLR = AttributesEnum.EarliestNonMedCompCmtClr.index();

    /**
     * This is the default constructor (do not remove).
     */
    public CrsEarliestVersionRowImpl() {
    }
}

