package com.novartis.ecrs.model.view;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Aug 15 20:14:08 IST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CrsEarliestVersionImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public CrsEarliestVersionImpl() {
    }
}

