package com.novartis.ecrs.model.view;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Aug 15 20:21:14 IST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CrsLatestVersionImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public CrsLatestVersionImpl() {
    }
}

