package com.novartis.ecrs.model.view;

import com.novartis.ecrs.model.entity.CrsRiskRelationsEOImpl;

import java.math.BigDecimal;

import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.domain.Timestamp;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Aug 14 22:28:08 IST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CrsRiskRelationVORowImpl extends ViewRowImpl {


    public static final int ENTITY_CRSRISKRELATIONSEO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        CrsId {
            protected Object get(CrsRiskRelationVORowImpl obj) {
                return obj.getCrsId();
            }

            protected void put(CrsRiskRelationVORowImpl obj, Object value) {
                obj.setCrsId((Long) value);
            }
        }
        ,
        CrsRiskId {
            protected Object get(CrsRiskRelationVORowImpl obj) {
                return obj.getCrsRiskId();
            }

            protected void put(CrsRiskRelationVORowImpl obj, Object value) {
                obj.setCrsRiskId((Long) value);
            }
        }
        ,
        MqmComment {
            protected Object get(CrsRiskRelationVORowImpl obj) {
                return obj.getMqmComment();
            }

            protected void put(CrsRiskRelationVORowImpl obj, Object value) {
                obj.setMqmComment((String) value);
            }
        }
        ,
        NonMeddraComponentComment {
            protected Object get(CrsRiskRelationVORowImpl obj) {
                return obj.getNonMeddraComponentComment();
            }

            protected void put(CrsRiskRelationVORowImpl obj, Object value) {
                obj.setNonMeddraComponentComment((String) value);
            }
        }
        ,
        SafetyTopicOfInterest {
            protected Object get(CrsRiskRelationVORowImpl obj) {
                return obj.getSafetyTopicOfInterest();
            }

            protected void put(CrsRiskRelationVORowImpl obj, Object value) {
                obj.setSafetyTopicOfInterest((String) value);
            }
        }
        ,
        SocDictContentEntryTs {
            protected Object get(CrsRiskRelationVORowImpl obj) {
                return obj.getSocDictContentEntryTs();
            }

            protected void put(CrsRiskRelationVORowImpl obj, Object value) {
                obj.setSocDictContentEntryTs((Timestamp) value);
            }
        }
        ,
        SocDictContentId {
            protected Object get(CrsRiskRelationVORowImpl obj) {
                return obj.getSocDictContentId();
            }

            protected void put(CrsRiskRelationVORowImpl obj, Object value) {
                obj.setSocDictContentId((Long) value);
            }
        }
        ,
        SocTerm {
            protected Object get(CrsRiskRelationVORowImpl obj) {
                return obj.getSocTerm();
            }

            protected void put(CrsRiskRelationVORowImpl obj, Object value) {
                obj.setSocTerm((String) value);
            }
        }
        ,
        UiVersionNumber {
            protected Object get(CrsRiskRelationVORowImpl obj) {
                return obj.getUiVersionNumber();
            }

            protected void put(CrsRiskRelationVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        RiskPurposeList {
            protected Object get(CrsRiskRelationVORowImpl obj) {
                return obj.getRiskPurposeList();
            }

            protected void put(CrsRiskRelationVORowImpl obj, Object value) {
                obj.setRiskPurposeList((String) value);
            }
        }
        ,
        CrsEffectiveDt {
            protected Object get(CrsRiskRelationVORowImpl obj) {
                return obj.getCrsEffectiveDt();
            }

            protected void put(CrsRiskRelationVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        DomainId {
            protected Object get(CrsRiskRelationVORowImpl obj) {
                return obj.getDomainId();
            }

            protected void put(CrsRiskRelationVORowImpl obj, Object value) {
                obj.setDomainId((Integer) value);
            }
        }
        ,
        CreatedBy {
            protected Object get(CrsRiskRelationVORowImpl obj) {
                return obj.getCreatedBy();
            }

            protected void put(CrsRiskRelationVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        CreationTs {
            protected Object get(CrsRiskRelationVORowImpl obj) {
                return obj.getCreationTs();
            }

            protected void put(CrsRiskRelationVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        ModifiedBy {
            protected Object get(CrsRiskRelationVORowImpl obj) {
                return obj.getModifiedBy();
            }

            protected void put(CrsRiskRelationVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        ModificationTs {
            protected Object get(CrsRiskRelationVORowImpl obj) {
                return obj.getModificationTs();
            }

            protected void put(CrsRiskRelationVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        SearchCriteriaDetails {
            protected Object get(CrsRiskRelationVORowImpl obj) {
                return obj.getSearchCriteriaDetails();
            }

            protected void put(CrsRiskRelationVORowImpl obj, Object value) {
                obj.setSearchCriteriaDetails((String) value);
            }
        }
        ,
        Adr {
            protected Object get(CrsRiskRelationVORowImpl obj) {
                return obj.getAdr();
            }

            protected void put(CrsRiskRelationVORowImpl obj, Object value) {
                obj.setAdr((String) value);
            }
        }
        ,
        SearchAppliedTo {
            protected Object get(CrsRiskRelationVORowImpl obj) {
                return obj.getSearchAppliedTo();
            }

            protected void put(CrsRiskRelationVORowImpl obj, Object value) {
                obj.setSearchAppliedTo((String) value);
            }
        }
        ,
        GenderCode {
            protected Object get(CrsRiskRelationVORowImpl obj) {
                return obj.getGenderCode();
            }

            protected void put(CrsRiskRelationVORowImpl obj, Object value) {
                obj.setGenderCode((String) value);
            }
        }
        ,
        CrsAgeGrpId {
            protected Object get(CrsRiskRelationVORowImpl obj) {
                return obj.getCrsAgeGrpId();
            }

            protected void put(CrsRiskRelationVORowImpl obj, Object value) {
                obj.setCrsAgeGrpId((BigDecimal) value);
            }
        }
        ,
        CrsAgeSubGrpId {
            protected Object get(CrsRiskRelationVORowImpl obj) {
                return obj.getCrsAgeSubGrpId();
            }

            protected void put(CrsRiskRelationVORowImpl obj, Object value) {
                obj.setCrsAgeSubGrpId((String) value);
            }
        }
        ,
        CrsRiskDefinitionsVO {
            protected Object get(CrsRiskRelationVORowImpl obj) {
                return obj.getCrsRiskDefinitionsVO();
            }

            protected void put(CrsRiskRelationVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        SocLOVO {
            protected Object get(CrsRiskRelationVORowImpl obj) {
                return obj.getSocLOVO();
            }

            protected void put(CrsRiskRelationVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        DomainOtherLOVVA {
            protected Object get(CrsRiskRelationVORowImpl obj) {
                return obj.getDomainOtherLOVVA();
            }

            protected void put(CrsRiskRelationVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        ADRVA {
            protected Object get(CrsRiskRelationVORowImpl obj) {
                return obj.getADRVA();
            }

            protected void put(CrsRiskRelationVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        SearchAppliedToVA {
            protected Object get(CrsRiskRelationVORowImpl obj) {
                return obj.getSearchAppliedToVA();
            }

            protected void put(CrsRiskRelationVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        GenderVA {
            protected Object get(CrsRiskRelationVORowImpl obj) {
                return obj.getGenderVA();
            }

            protected void put(CrsRiskRelationVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        AgeGroupVA {
            protected Object get(CrsRiskRelationVORowImpl obj) {
                return obj.getAgeGroupVA();
            }

            protected void put(CrsRiskRelationVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        AgeSubGroupVA {
            protected Object get(CrsRiskRelationVORowImpl obj) {
                return obj.getAgeSubGroupVA();
            }

            protected void put(CrsRiskRelationVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        DomainLOVVA {
            protected Object get(CrsRiskRelationVORowImpl obj) {
                return obj.getDomainLOVVA();
            }

            protected void put(CrsRiskRelationVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        ;
        private static int firstIndex = 0;


        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }


        protected abstract Object get(CrsRiskRelationVORowImpl object);

        protected abstract void put(CrsRiskRelationVORowImpl object, Object value);
    }


    public static final int CRSID = AttributesEnum.CrsId.index();
    public static final int CRSRISKID = AttributesEnum.CrsRiskId.index();
    public static final int MQMCOMMENT = AttributesEnum.MqmComment.index();
    public static final int NONMEDDRACOMPONENTCOMMENT = AttributesEnum.NonMeddraComponentComment.index();
    public static final int SAFETYTOPICOFINTEREST = AttributesEnum.SafetyTopicOfInterest.index();
    public static final int SOCDICTCONTENTENTRYTS = AttributesEnum.SocDictContentEntryTs.index();
    public static final int SOCDICTCONTENTID = AttributesEnum.SocDictContentId.index();
    public static final int SOCTERM = AttributesEnum.SocTerm.index();
    public static final int UIVERSIONNUMBER = AttributesEnum.UiVersionNumber.index();
    public static final int RISKPURPOSELIST = AttributesEnum.RiskPurposeList.index();
    public static final int CRSEFFECTIVEDT = AttributesEnum.CrsEffectiveDt.index();
    public static final int DOMAINID = AttributesEnum.DomainId.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONTS = AttributesEnum.CreationTs.index();
    public static final int MODIFIEDBY = AttributesEnum.ModifiedBy.index();
    public static final int MODIFICATIONTS = AttributesEnum.ModificationTs.index();
    public static final int SEARCHCRITERIADETAILS = AttributesEnum.SearchCriteriaDetails.index();
    public static final int ADR = AttributesEnum.Adr.index();
    public static final int SEARCHAPPLIEDTO = AttributesEnum.SearchAppliedTo.index();
    public static final int GENDERCODE = AttributesEnum.GenderCode.index();
    public static final int CRSAGEGRPID = AttributesEnum.CrsAgeGrpId.index();
    public static final int CRSAGESUBGRPID = AttributesEnum.CrsAgeSubGrpId.index();
    public static final int CRSRISKDEFINITIONSVO = AttributesEnum.CrsRiskDefinitionsVO.index();
    public static final int SOCLOVO = AttributesEnum.SocLOVO.index();
    public static final int DOMAINOTHERLOVVA = AttributesEnum.DomainOtherLOVVA.index();
    public static final int ADRVA = AttributesEnum.ADRVA.index();
    public static final int SEARCHAPPLIEDTOVA = AttributesEnum.SearchAppliedToVA.index();
    public static final int GENDERVA = AttributesEnum.GenderVA.index();
    public static final int AGEGROUPVA = AttributesEnum.AgeGroupVA.index();
    public static final int AGESUBGROUPVA = AttributesEnum.AgeSubGroupVA.index();
    public static final int DOMAINLOVVA = AttributesEnum.DomainLOVVA.index();

    /**
     * This is the default constructor (do not remove).
     */
    public CrsRiskRelationVORowImpl() {
    }

    /**
     * Gets CrsRiskRelationsEO entity object.
     * @return the CrsRiskRelationsEO
     */
    public CrsRiskRelationsEOImpl getCrsRiskRelationsEO() {
        return (CrsRiskRelationsEOImpl)getEntity(ENTITY_CRSRISKRELATIONSEO);
    }

    /**
     * Gets the attribute value for CRS_ID using the alias name CrsId.
     * @return the CRS_ID
     */
    public Long getCrsId() {
        return (Long) getAttributeInternal(CRSID);
    }

    /**
     * Sets <code>value</code> as attribute value for CRS_ID using the alias name CrsId.
     * @param value value to set the CRS_ID
     */
    public void setCrsId(Long value) {
        setAttributeInternal(CRSID, value);
    }

    /**
     * Gets the attribute value for CRS_RISK_ID using the alias name CrsRiskId.
     * @return the CRS_RISK_ID
     */
    public Long getCrsRiskId() {
        return (Long) getAttributeInternal(CRSRISKID);
    }

    /**
     * Sets <code>value</code> as attribute value for CRS_RISK_ID using the alias name CrsRiskId.
     * @param value value to set the CRS_RISK_ID
     */
    public void setCrsRiskId(Long value) {
        setAttributeInternal(CRSRISKID, value);
    }

    /**
     * Gets the attribute value for MQM_COMMENT using the alias name MqmComment.
     * @return the MQM_COMMENT
     */
    public String getMqmComment() {
        return (String) getAttributeInternal(MQMCOMMENT);
    }

    /**
     * Sets <code>value</code> as attribute value for MQM_COMMENT using the alias name MqmComment.
     * @param value value to set the MQM_COMMENT
     */
    public void setMqmComment(String value) {
        setAttributeInternal(MQMCOMMENT, value);
    }

    /**
     * Gets the attribute value for NON_MEDDRA_COMPONENT_COMMENT using the alias name NonMeddraComponentComment.
     * @return the NON_MEDDRA_COMPONENT_COMMENT
     */
    public String getNonMeddraComponentComment() {
        return (String) getAttributeInternal(NONMEDDRACOMPONENTCOMMENT);
    }

    /**
     * Sets <code>value</code> as attribute value for NON_MEDDRA_COMPONENT_COMMENT using the alias name NonMeddraComponentComment.
     * @param value value to set the NON_MEDDRA_COMPONENT_COMMENT
     */
    public void setNonMeddraComponentComment(String value) {
        setAttributeInternal(NONMEDDRACOMPONENTCOMMENT, value);
    }

    /**
     * Gets the attribute value for SAFETY_TOPIC_OF_INTEREST using the alias name SafetyTopicOfInterest.
     * @return the SAFETY_TOPIC_OF_INTEREST
     */
    public String getSafetyTopicOfInterest() {
        return (String) getAttributeInternal(SAFETYTOPICOFINTEREST);
    }

    /**
     * Sets <code>value</code> as attribute value for SAFETY_TOPIC_OF_INTEREST using the alias name SafetyTopicOfInterest.
     * @param value value to set the SAFETY_TOPIC_OF_INTEREST
     */
    public void setSafetyTopicOfInterest(String value) {
        setAttributeInternal(SAFETYTOPICOFINTEREST, value);
    }

    /**
     * Gets the attribute value for SOC_DICT_CONTENT_ENTRY_TS using the alias name SocDictContentEntryTs.
     * @return the SOC_DICT_CONTENT_ENTRY_TS
     */
    public Timestamp getSocDictContentEntryTs() {
        return (Timestamp) getAttributeInternal(SOCDICTCONTENTENTRYTS);
    }

    /**
     * Sets <code>value</code> as attribute value for SOC_DICT_CONTENT_ENTRY_TS using the alias name SocDictContentEntryTs.
     * @param value value to set the SOC_DICT_CONTENT_ENTRY_TS
     */
    public void setSocDictContentEntryTs(Timestamp value) {
        setAttributeInternal(SOCDICTCONTENTENTRYTS, value);
    }

    /**
     * Gets the attribute value for SOC_DICT_CONTENT_ID using the alias name SocDictContentId.
     * @return the SOC_DICT_CONTENT_ID
     */
    public Long getSocDictContentId() {
        return (Long) getAttributeInternal(SOCDICTCONTENTID);
    }

    /**
     * Sets <code>value</code> as attribute value for SOC_DICT_CONTENT_ID using the alias name SocDictContentId.
     * @param value value to set the SOC_DICT_CONTENT_ID
     */
    public void setSocDictContentId(Long value) {
        setAttributeInternal(SOCDICTCONTENTID, value);
    }

    /**
     * Gets the attribute value for SOC_TERM using the alias name SocTerm.
     * @return the SOC_TERM
     */
    public String getSocTerm() {
        return (String) getAttributeInternal(SOCTERM);
    }

    /**
     * Sets <code>value</code> as attribute value for SOC_TERM using the alias name SocTerm.
     * @param value value to set the SOC_TERM
     */
    public void setSocTerm(String value) {
        setAttributeInternal(SOCTERM, value);
    }

    /**
     * Gets the attribute value for UI_VERSION_NUMBER using the alias name UiVersionNumber.
     * @return the UI_VERSION_NUMBER
     */
    public Integer getUiVersionNumber() {
        return (Integer) getAttributeInternal(UIVERSIONNUMBER);
    }


    /**
     * Gets the attribute value for RISK_PURPOSE_LIST using the alias name RiskPurposeList.
     * @return the RISK_PURPOSE_LIST
     */
    public String getRiskPurposeList() {
        return (String) getAttributeInternal(RISKPURPOSELIST);
    }

    /**
     * Sets <code>value</code> as attribute value for RISK_PURPOSE_LIST using the alias name RiskPurposeList.
     * @param value value to set the RISK_PURPOSE_LIST
     */
    public void setRiskPurposeList(String value) {
        setAttributeInternal(RISKPURPOSELIST, value);
    }

    /**
     * Gets the attribute value for CRS_EFFECTIVE_DT using the alias name CrsEffectiveDt.
     * @return the CRS_EFFECTIVE_DT
     */
    public Timestamp getCrsEffectiveDt() {
        return (Timestamp) getAttributeInternal(CRSEFFECTIVEDT);
    }


    /**
     * Gets the attribute value for DOMAIN_ID using the alias name DomainId.
     * @return the DOMAIN_ID
     */
    public Integer getDomainId() {
        return (Integer) getAttributeInternal(DOMAINID);
    }

    /**
     * Sets <code>value</code> as attribute value for DOMAIN_ID using the alias name DomainId.
     * @param value value to set the DOMAIN_ID
     */
    public void setDomainId(Integer value) {
        setAttributeInternal(DOMAINID, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }


    /**
     * Gets the attribute value for CREATION_TS using the alias name CreationTs.
     * @return the CREATION_TS
     */
    public Timestamp getCreationTs() {
        return (Timestamp) getAttributeInternal(CREATIONTS);
    }


    /**
     * Gets the attribute value for MODIFIED_BY using the alias name ModifiedBy.
     * @return the MODIFIED_BY
     */
    public String getModifiedBy() {
        return (String) getAttributeInternal(MODIFIEDBY);
    }


    /**
     * Gets the attribute value for MODIFICATION_TS using the alias name ModificationTs.
     * @return the MODIFICATION_TS
     */
    public Timestamp getModificationTs() {
        return (Timestamp) getAttributeInternal(MODIFICATIONTS);
    }


    /**
     * Gets the attribute value for SEARCH_CRITERIA_DETAILS using the alias name SearchCriteriaDetails.
     * @return the SEARCH_CRITERIA_DETAILS
     */
    public String getSearchCriteriaDetails() {
        return (String) getAttributeInternal(SEARCHCRITERIADETAILS);
    }

    /**
     * Sets <code>value</code> as attribute value for SEARCH_CRITERIA_DETAILS using the alias name SearchCriteriaDetails.
     * @param value value to set the SEARCH_CRITERIA_DETAILS
     */
    public void setSearchCriteriaDetails(String value) {
        setAttributeInternal(SEARCHCRITERIADETAILS, value);
    }

    /**
     * Gets the attribute value for ADR using the alias name Adr.
     * @return the ADR
     */
    public String getAdr() {
        return (String) getAttributeInternal(ADR);
    }

    /**
     * Sets <code>value</code> as attribute value for ADR using the alias name Adr.
     * @param value value to set the ADR
     */
    public void setAdr(String value) {
        setAttributeInternal(ADR, value);
    }

    /**
     * Gets the attribute value for SEARCH_APPLIED_TO using the alias name SearchAppliedTo.
     * @return the SEARCH_APPLIED_TO
     */
    public String getSearchAppliedTo() {
        return (String) getAttributeInternal(SEARCHAPPLIEDTO);
    }

    /**
     * Sets <code>value</code> as attribute value for SEARCH_APPLIED_TO using the alias name SearchAppliedTo.
     * @param value value to set the SEARCH_APPLIED_TO
     */
    public void setSearchAppliedTo(String value) {
        setAttributeInternal(SEARCHAPPLIEDTO, value);
    }


    /**
     * Gets the attribute value for GENDER_CODE using the alias name GenderCode.
     * @return the GENDER_CODE
     */
    public String getGenderCode() {
        return (String) getAttributeInternal(GENDERCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for GENDER_CODE using the alias name GenderCode.
     * @param value value to set the GENDER_CODE
     */
    public void setGenderCode(String value) {
        setAttributeInternal(GENDERCODE, value);
    }

    /**
     * Gets the attribute value for CRS_AGE_GRP_ID using the alias name CrsAgeGrpId.
     * @return the CRS_AGE_GRP_ID
     */
    public BigDecimal getCrsAgeGrpId() {
        return (BigDecimal) getAttributeInternal(CRSAGEGRPID);
    }

    /**
     * Sets <code>value</code> as attribute value for CRS_AGE_GRP_ID using the alias name CrsAgeGrpId.
     * @param value value to set the CRS_AGE_GRP_ID
     */
    public void setCrsAgeGrpId(BigDecimal value) {
        setAttributeInternal(CRSAGEGRPID, value);
    }

    /**
     * Gets the attribute value for CRS_AGE_SUB_GRP_ID using the alias name CrsAgeSubGrpId.
     * @return the CRS_AGE_SUB_GRP_ID
     */
    public String getCrsAgeSubGrpId() {
        return (String) getAttributeInternal(CRSAGESUBGRPID);
    }

    /**
     * Sets <code>value</code> as attribute value for CRS_AGE_SUB_GRP_ID using the alias name CrsAgeSubGrpId.
     * @param value value to set the CRS_AGE_SUB_GRP_ID
     */
    public void setCrsAgeSubGrpId(String value) {
        setAttributeInternal(CRSAGESUBGRPID, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link CrsRiskDefinitionsVO.
     */
    public RowIterator getCrsRiskDefinitionsVO() {
        return (RowIterator)getAttributeInternal(CRSRISKDEFINITIONSVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> SocLOVO.
     */
    public RowSet getSocLOVO() {
        return (RowSet)getAttributeInternal(SOCLOVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> DomainOtherLOVVA.
     */
    public RowSet getDomainOtherLOVVA() {
        return (RowSet) getAttributeInternal(DOMAINOTHERLOVVA);
    }

    /**
     * Gets the view accessor <code>RowSet</code> ADRVA.
     */
    public RowSet getADRVA() {
        return (RowSet) getAttributeInternal(ADRVA);
    }

    /**
     * Gets the view accessor <code>RowSet</code> SearchAppliedToVA.
     */
    public RowSet getSearchAppliedToVA() {
        return (RowSet) getAttributeInternal(SEARCHAPPLIEDTOVA);
    }

    /**
     * Gets the view accessor <code>RowSet</code> GenderVA.
     */
    public RowSet getGenderVA() {
        return (RowSet) getAttributeInternal(GENDERVA);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AgeGroupVA.
     */
    public RowSet getAgeGroupVA() {
        return (RowSet) getAttributeInternal(AGEGROUPVA);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AgeSubGroupVA.
     */
    public RowSet getAgeSubGroupVA() {
        return (RowSet) getAttributeInternal(AGESUBGROUPVA);
    }

    /**
     * Gets the view accessor <code>RowSet</code> DomainLOVVA.
     */
    public RowSet getDomainLOVVA() {
        return (RowSet) getAttributeInternal(DOMAINLOVVA);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
