package com.novartis.ecrs.model.view;

import com.novartis.ecrs.model.entity.CrsRiskDefinitionsEOImpl;

import oracle.jbo.domain.Timestamp;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Jul 04 22:37:53 IST 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CrsRiskDefinitionsVORowImpl extends ViewRowImpl {
    public static final int ENTITY_CRSRISKDEFINITIONSEO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        CrsRiskDefnId {
            protected Object get(CrsRiskDefinitionsVORowImpl obj) {
                return obj.getCrsRiskDefnId();
            }

            protected void put(CrsRiskDefinitionsVORowImpl obj, Object value) {
                obj.setCrsRiskDefnId((Long) value);
            }
        }
        ,
        CrsRiskId {
            protected Object get(CrsRiskDefinitionsVORowImpl obj) {
                return obj.getCrsRiskId();
            }

            protected void put(CrsRiskDefinitionsVORowImpl obj, Object value) {
                obj.setCrsRiskId((Long) value);
            }
        }
        ,
        MeddraCode {
            protected Object get(CrsRiskDefinitionsVORowImpl obj) {
                return obj.getMeddraCode();
            }

            protected void put(CrsRiskDefinitionsVORowImpl obj, Object value) {
                obj.setMeddraCode((String) value);
            }
        }
        ,
        MeddraLevel {
            protected Object get(CrsRiskDefinitionsVORowImpl obj) {
                return obj.getMeddraLevel();
            }

            protected void put(CrsRiskDefinitionsVORowImpl obj, Object value) {
                obj.setMeddraLevel((String) value);
            }
        }
        ,
        MeddraQualifier {
            protected Object get(CrsRiskDefinitionsVORowImpl obj) {
                return obj.getMeddraQualifier();
            }

            protected void put(CrsRiskDefinitionsVORowImpl obj, Object value) {
                obj.setMeddraQualifier((String) value);
            }
        }
        ,
        MeddraTerm {
            protected Object get(CrsRiskDefinitionsVORowImpl obj) {
                return obj.getMeddraTerm();
            }

            protected void put(CrsRiskDefinitionsVORowImpl obj, Object value) {
                obj.setMeddraTerm((String) value);
            }
        }
        ,
        MeddraVersion {
            protected Object get(CrsRiskDefinitionsVORowImpl obj) {
                return obj.getMeddraVersion();
            }

            protected void put(CrsRiskDefinitionsVORowImpl obj, Object value) {
                obj.setMeddraVersion((String) value);
            }
        }
        ,
        MeddraVersionDate {
            protected Object get(CrsRiskDefinitionsVORowImpl obj) {
                return obj.getMeddraVersionDate();
            }

            protected void put(CrsRiskDefinitionsVORowImpl obj, Object value) {
                obj.setMeddraVersionDate((Timestamp) value);
            }
        }
        ,
        TmsDictContentEntryTs {
            protected Object get(CrsRiskDefinitionsVORowImpl obj) {
                return obj.getTmsDictContentEntryTs();
            }

            protected void put(CrsRiskDefinitionsVORowImpl obj, Object value) {
                obj.setTmsDictContentEntryTs((Timestamp) value);
            }
        }
        ,
        TmsDictContentId {
            protected Object get(CrsRiskDefinitionsVORowImpl obj) {
                return obj.getTmsDictContentId();
            }

            protected void put(CrsRiskDefinitionsVORowImpl obj, Object value) {
                obj.setTmsDictContentId((Long) value);
            }
        }
        ,
        TmsEndTs {
            protected Object get(CrsRiskDefinitionsVORowImpl obj) {
                return obj.getTmsEndTs();
            }

            protected void put(CrsRiskDefinitionsVORowImpl obj, Object value) {
                obj.setTmsEndTs((Timestamp) value);
            }
        }
        ,
        TmsUpdateFlag {
            protected Object get(CrsRiskDefinitionsVORowImpl obj) {
                return obj.getTmsUpdateFlag();
            }

            protected void put(CrsRiskDefinitionsVORowImpl obj, Object value) {
                obj.setTmsUpdateFlag((String) value);
            }
        }
        ,
        TmsUpdateFlagDt {
            protected Object get(CrsRiskDefinitionsVORowImpl obj) {
                return obj.getTmsUpdateFlagDt();
            }

            protected void put(CrsRiskDefinitionsVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        MeddraDict {
            protected Object get(CrsRiskDefinitionsVORowImpl obj) {
                return obj.getMeddraDict();
            }

            protected void put(CrsRiskDefinitionsVORowImpl obj, Object value) {
                obj.setMeddraDict((String) value);
            }
        }
        ,
        MeddraExtension {
            protected Object get(CrsRiskDefinitionsVORowImpl obj) {
                return obj.getMeddraExtension();
            }

            protected void put(CrsRiskDefinitionsVORowImpl obj, Object value) {
                obj.setMeddraExtension((String) value);
            }
        }
        ,
        CrsEffectiveDt {
            protected Object get(CrsRiskDefinitionsVORowImpl obj) {
                return obj.getCrsEffectiveDt();
            }

            protected void put(CrsRiskDefinitionsVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        CreatedBy {
            protected Object get(CrsRiskDefinitionsVORowImpl obj) {
                return obj.getCreatedBy();
            }

            protected void put(CrsRiskDefinitionsVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        UiVersionNumber {
            protected Object get(CrsRiskDefinitionsVORowImpl obj) {
                return obj.getUiVersionNumber();
            }

            protected void put(CrsRiskDefinitionsVORowImpl obj, Object value) {
                obj.setUiVersionNumber((Integer) value);
            }
        }
        ,
        CreationTs {
            protected Object get(CrsRiskDefinitionsVORowImpl obj) {
                return obj.getCreationTs();
            }

            protected void put(CrsRiskDefinitionsVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        ModifiedBy {
            protected Object get(CrsRiskDefinitionsVORowImpl obj) {
                return obj.getModifiedBy();
            }

            protected void put(CrsRiskDefinitionsVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        ModificationTs {
            protected Object get(CrsRiskDefinitionsVORowImpl obj) {
                return obj.getModificationTs();
            }

            protected void put(CrsRiskDefinitionsVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        MeddraQualifierUpdFlag {
            protected Object get(CrsRiskDefinitionsVORowImpl obj) {
                return obj.getMeddraQualifierUpdFlag();
            }

            protected void put(CrsRiskDefinitionsVORowImpl obj, Object value) {
                obj.setMeddraQualifierUpdFlag((String) value);
            }
        }
        ,
        CrsQualifier {
            protected Object get(CrsRiskDefinitionsVORowImpl obj) {
                return obj.getCrsQualifier();
            }

            protected void put(CrsRiskDefinitionsVORowImpl obj, Object value) {
                obj.setCrsQualifier((String) value);
            }
        }
        ,
        TmsStatus {
            protected Object get(CrsRiskDefinitionsVORowImpl obj) {
                return obj.getTmsStatus();
            }

            protected void put(CrsRiskDefinitionsVORowImpl obj, Object value) {
                obj.setTmsStatus((String) value);
            }
        }
        ,
        SelectAttr {
            protected Object get(CrsRiskDefinitionsVORowImpl obj) {
                return obj.getSelectAttr();
            }

            protected void put(CrsRiskDefinitionsVORowImpl obj, Object value) {
                obj.setSelectAttr((Boolean) value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected abstract Object get(CrsRiskDefinitionsVORowImpl object);

        protected abstract void put(CrsRiskDefinitionsVORowImpl object, Object value);

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int CRSRISKDEFNID = AttributesEnum.CrsRiskDefnId.index();
    public static final int CRSRISKID = AttributesEnum.CrsRiskId.index();
    public static final int MEDDRACODE = AttributesEnum.MeddraCode.index();
    public static final int MEDDRALEVEL = AttributesEnum.MeddraLevel.index();
    public static final int MEDDRAQUALIFIER = AttributesEnum.MeddraQualifier.index();
    public static final int MEDDRATERM = AttributesEnum.MeddraTerm.index();
    public static final int MEDDRAVERSION = AttributesEnum.MeddraVersion.index();
    public static final int MEDDRAVERSIONDATE = AttributesEnum.MeddraVersionDate.index();
    public static final int TMSDICTCONTENTENTRYTS = AttributesEnum.TmsDictContentEntryTs.index();
    public static final int TMSDICTCONTENTID = AttributesEnum.TmsDictContentId.index();
    public static final int TMSENDTS = AttributesEnum.TmsEndTs.index();
    public static final int TMSUPDATEFLAG = AttributesEnum.TmsUpdateFlag.index();
    public static final int TMSUPDATEFLAGDT = AttributesEnum.TmsUpdateFlagDt.index();
    public static final int MEDDRADICT = AttributesEnum.MeddraDict.index();
    public static final int MEDDRAEXTENSION = AttributesEnum.MeddraExtension.index();
    public static final int CRSEFFECTIVEDT = AttributesEnum.CrsEffectiveDt.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int UIVERSIONNUMBER = AttributesEnum.UiVersionNumber.index();
    public static final int CREATIONTS = AttributesEnum.CreationTs.index();
    public static final int MODIFIEDBY = AttributesEnum.ModifiedBy.index();
    public static final int MODIFICATIONTS = AttributesEnum.ModificationTs.index();
    public static final int MEDDRAQUALIFIERUPDFLAG = AttributesEnum.MeddraQualifierUpdFlag.index();
    public static final int CRSQUALIFIER = AttributesEnum.CrsQualifier.index();
    public static final int TMSSTATUS = AttributesEnum.TmsStatus.index();
    public static final int SELECTATTR = AttributesEnum.SelectAttr.index();

    /**
     * This is the default constructor (do not remove).
     */
    public CrsRiskDefinitionsVORowImpl() {
    }

    /**
     * Gets CrsRiskDefinitionsEO entity object.
     * @return the CrsRiskDefinitionsEO
     */
    public CrsRiskDefinitionsEOImpl getCrsRiskDefinitionsEO() {
        return (CrsRiskDefinitionsEOImpl) getEntity(ENTITY_CRSRISKDEFINITIONSEO);
    }

    /**
     * Gets the attribute value for CRS_RISK_DEFN_ID using the alias name CrsRiskDefnId.
     * @return the CRS_RISK_DEFN_ID
     */
    public Long getCrsRiskDefnId() {
        return (Long) getAttributeInternal(CRSRISKDEFNID);
    }

    /**
     * Sets <code>value</code> as attribute value for CRS_RISK_DEFN_ID using the alias name CrsRiskDefnId.
     * @param value value to set the CRS_RISK_DEFN_ID
     */
    public void setCrsRiskDefnId(Long value) {
        setAttributeInternal(CRSRISKDEFNID, value);
    }

    /**
     * Gets the attribute value for CRS_RISK_ID using the alias name CrsRiskId.
     * @return the CRS_RISK_ID
     */
    public Long getCrsRiskId() {
        return (Long) getAttributeInternal(CRSRISKID);
    }

    /**
     * Sets <code>value</code> as attribute value for CRS_RISK_ID using the alias name CrsRiskId.
     * @param value value to set the CRS_RISK_ID
     */
    public void setCrsRiskId(Long value) {
        setAttributeInternal(CRSRISKID, value);
    }

    /**
     * Gets the attribute value for MEDDRA_CODE using the alias name MeddraCode.
     * @return the MEDDRA_CODE
     */
    public String getMeddraCode() {
        return (String) getAttributeInternal(MEDDRACODE);
    }

    /**
     * Sets <code>value</code> as attribute value for MEDDRA_CODE using the alias name MeddraCode.
     * @param value value to set the MEDDRA_CODE
     */
    public void setMeddraCode(String value) {
        setAttributeInternal(MEDDRACODE, value);
    }

    /**
     * Gets the attribute value for MEDDRA_LEVEL using the alias name MeddraLevel.
     * @return the MEDDRA_LEVEL
     */
    public String getMeddraLevel() {
        return (String) getAttributeInternal(MEDDRALEVEL);
    }

    /**
     * Sets <code>value</code> as attribute value for MEDDRA_LEVEL using the alias name MeddraLevel.
     * @param value value to set the MEDDRA_LEVEL
     */
    public void setMeddraLevel(String value) {
        setAttributeInternal(MEDDRALEVEL, value);
    }

    /**
     * Gets the attribute value for MEDDRA_QUALIFIER using the alias name MeddraQualifier.
     * @return the MEDDRA_QUALIFIER
     */
    public String getMeddraQualifier() {
        return (String) getAttributeInternal(MEDDRAQUALIFIER);
    }

    /**
     * Sets <code>value</code> as attribute value for MEDDRA_QUALIFIER using the alias name MeddraQualifier.
     * @param value value to set the MEDDRA_QUALIFIER
     */
    public void setMeddraQualifier(String value) {
        setAttributeInternal(MEDDRAQUALIFIER, value);
    }

    /**
     * Gets the attribute value for MEDDRA_TERM using the alias name MeddraTerm.
     * @return the MEDDRA_TERM
     */
    public String getMeddraTerm() {
        return (String) getAttributeInternal(MEDDRATERM);
    }

    /**
     * Sets <code>value</code> as attribute value for MEDDRA_TERM using the alias name MeddraTerm.
     * @param value value to set the MEDDRA_TERM
     */
    public void setMeddraTerm(String value) {
        setAttributeInternal(MEDDRATERM, value);
    }

    /**
     * Gets the attribute value for MEDDRA_VERSION using the alias name MeddraVersion.
     * @return the MEDDRA_VERSION
     */
    public String getMeddraVersion() {
        return (String) getAttributeInternal(MEDDRAVERSION);
    }

    /**
     * Sets <code>value</code> as attribute value for MEDDRA_VERSION using the alias name MeddraVersion.
     * @param value value to set the MEDDRA_VERSION
     */
    public void setMeddraVersion(String value) {
        setAttributeInternal(MEDDRAVERSION, value);
    }

    /**
     * Gets the attribute value for MEDDRA_VERSION_DATE using the alias name MeddraVersionDate.
     * @return the MEDDRA_VERSION_DATE
     */
    public Timestamp getMeddraVersionDate() {
        return (Timestamp) getAttributeInternal(MEDDRAVERSIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for MEDDRA_VERSION_DATE using the alias name MeddraVersionDate.
     * @param value value to set the MEDDRA_VERSION_DATE
     */
    public void setMeddraVersionDate(Timestamp value) {
        setAttributeInternal(MEDDRAVERSIONDATE, value);
    }

    /**
     * Gets the attribute value for TMS_DICT_CONTENT_ENTRY_TS using the alias name TmsDictContentEntryTs.
     * @return the TMS_DICT_CONTENT_ENTRY_TS
     */
    public Timestamp getTmsDictContentEntryTs() {
        return (Timestamp) getAttributeInternal(TMSDICTCONTENTENTRYTS);
    }

    /**
     * Sets <code>value</code> as attribute value for TMS_DICT_CONTENT_ENTRY_TS using the alias name TmsDictContentEntryTs.
     * @param value value to set the TMS_DICT_CONTENT_ENTRY_TS
     */
    public void setTmsDictContentEntryTs(Timestamp value) {
        setAttributeInternal(TMSDICTCONTENTENTRYTS, value);
    }

    /**
     * Gets the attribute value for TMS_DICT_CONTENT_ID using the alias name TmsDictContentId.
     * @return the TMS_DICT_CONTENT_ID
     */
    public Long getTmsDictContentId() {
        return (Long) getAttributeInternal(TMSDICTCONTENTID);
    }

    /**
     * Sets <code>value</code> as attribute value for TMS_DICT_CONTENT_ID using the alias name TmsDictContentId.
     * @param value value to set the TMS_DICT_CONTENT_ID
     */
    public void setTmsDictContentId(Long value) {
        setAttributeInternal(TMSDICTCONTENTID, value);
    }

    /**
     * Gets the attribute value for TMS_END_TS using the alias name TmsEndTs.
     * @return the TMS_END_TS
     */
    public Timestamp getTmsEndTs() {
        return (Timestamp) getAttributeInternal(TMSENDTS);
    }

    /**
     * Sets <code>value</code> as attribute value for TMS_END_TS using the alias name TmsEndTs.
     * @param value value to set the TMS_END_TS
     */
    public void setTmsEndTs(Timestamp value) {
        setAttributeInternal(TMSENDTS, value);
    }

    /**
     * Gets the attribute value for TMS_UPDATE_FLAG using the alias name TmsUpdateFlag.
     * @return the TMS_UPDATE_FLAG
     */
    public String getTmsUpdateFlag() {
        return (String) getAttributeInternal(TMSUPDATEFLAG);
    }

    /**
     * Sets <code>value</code> as attribute value for TMS_UPDATE_FLAG using the alias name TmsUpdateFlag.
     * @param value value to set the TMS_UPDATE_FLAG
     */
    public void setTmsUpdateFlag(String value) {
        setAttributeInternal(TMSUPDATEFLAG, value);
    }

    /**
     * Gets the attribute value for TMS_UPDATE_FLAG_DT using the alias name TmsUpdateFlagDt.
     * @return the TMS_UPDATE_FLAG_DT
     */
    public Timestamp getTmsUpdateFlagDt() {
        return (Timestamp) getAttributeInternal(TMSUPDATEFLAGDT);
    }

    /**
     * Gets the attribute value for MEDDRA_DICT using the alias name MeddraDict.
     * @return the MEDDRA_DICT
     */
    public String getMeddraDict() {
        return (String) getAttributeInternal(MEDDRADICT);
    }

    /**
     * Sets <code>value</code> as attribute value for MEDDRA_DICT using the alias name MeddraDict.
     * @param value value to set the MEDDRA_DICT
     */
    public void setMeddraDict(String value) {
        setAttributeInternal(MEDDRADICT, value);
    }

    /**
     * Gets the attribute value for MEDDRA_EXTENSION using the alias name MeddraExtension.
     * @return the MEDDRA_EXTENSION
     */
    public String getMeddraExtension() {
        return (String) getAttributeInternal(MEDDRAEXTENSION);
    }

    /**
     * Sets <code>value</code> as attribute value for MEDDRA_EXTENSION using the alias name MeddraExtension.
     * @param value value to set the MEDDRA_EXTENSION
     */
    public void setMeddraExtension(String value) {
        setAttributeInternal(MEDDRAEXTENSION, value);
    }

    /**
     * Gets the attribute value for CRS_EFFECTIVE_DT using the alias name CrsEffectiveDt.
     * @return the CRS_EFFECTIVE_DT
     */
    public Timestamp getCrsEffectiveDt() {
        return (Timestamp) getAttributeInternal(CRSEFFECTIVEDT);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Gets the attribute value for UI_VERSION_NUMBER using the alias name UiVersionNumber.
     * @return the UI_VERSION_NUMBER
     */
    public Integer getUiVersionNumber() {
        return (Integer) getAttributeInternal(UIVERSIONNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for UI_VERSION_NUMBER using the alias name UiVersionNumber.
     * @param value value to set the UI_VERSION_NUMBER
     */
    public void setUiVersionNumber(Integer value) {
        setAttributeInternal(UIVERSIONNUMBER, value);
    }

    /**
     * Gets the attribute value for CREATION_TS using the alias name CreationTs.
     * @return the CREATION_TS
     */
    public Timestamp getCreationTs() {
        return (Timestamp) getAttributeInternal(CREATIONTS);
    }

    /**
     * Gets the attribute value for MODIFIED_BY using the alias name ModifiedBy.
     * @return the MODIFIED_BY
     */
    public String getModifiedBy() {
        return (String) getAttributeInternal(MODIFIEDBY);
    }

    /**
     * Gets the attribute value for MODIFICATION_TS using the alias name ModificationTs.
     * @return the MODIFICATION_TS
     */
    public Timestamp getModificationTs() {
        return (Timestamp) getAttributeInternal(MODIFICATIONTS);
    }

    /**
     * Gets the attribute value for MEDDRA_QUALIFIER_UPD_FLAG using the alias name MeddraQualifierUpdFlag.
     * @return the MEDDRA_QUALIFIER_UPD_FLAG
     */
    public String getMeddraQualifierUpdFlag() {
        return (String) getAttributeInternal(MEDDRAQUALIFIERUPDFLAG);
    }

    /**
     * Sets <code>value</code> as attribute value for MEDDRA_QUALIFIER_UPD_FLAG using the alias name MeddraQualifierUpdFlag.
     * @param value value to set the MEDDRA_QUALIFIER_UPD_FLAG
     */
    public void setMeddraQualifierUpdFlag(String value) {
        setAttributeInternal(MEDDRAQUALIFIERUPDFLAG, value);
    }

    /**
     * Gets the attribute value for CRS_QUALIFIER using the alias name CrsQualifier.
     * @return the CRS_QUALIFIER
     */
    public String getCrsQualifier() {
        return (String) getAttributeInternal(CRSQUALIFIER);
    }

    /**
     * Sets <code>value</code> as attribute value for CRS_QUALIFIER using the alias name CrsQualifier.
     * @param value value to set the CRS_QUALIFIER
     */
    public void setCrsQualifier(String value) {
        setAttributeInternal(CRSQUALIFIER, value);
    }

    /**
     * Gets the attribute value for TMS_STATUS using the alias name TmsStatus.
     * @return the TMS_STATUS
     */
    public String getTmsStatus() {
        return (String) getAttributeInternal(TMSSTATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for TMS_STATUS using the alias name TmsStatus.
     * @param value value to set the TMS_STATUS
     */
    public void setTmsStatus(String value) {
        setAttributeInternal(TMSSTATUS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SelectAttr.
     * @return the SelectAttr
     */
    public Boolean getSelectAttr() {
        return (Boolean) getAttributeInternal(SELECTATTR);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SelectAttr.
     * @param value value to set the  SelectAttr
     */
    public void setSelectAttr(Boolean value) {
        setAttributeInternal(SELECTATTR, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}

