package com.novartis.ecrs.model.view;

import com.novartis.ecrs.model.entity.CrsRiskDefinitionsEOImpl;

import com.novartis.ecrs.model.view.common.CrsRiskDefinitionsVO;

import java.util.Iterator;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Aug 19 14:01:50 IST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CrsRiskDefinitionsVOImpl extends ViewObjectImpl implements CrsRiskDefinitionsVO {
    /**
     * This is the default constructor (do not remove).
     */
    public CrsRiskDefinitionsVOImpl() {
    }
    
    public void undoDelete(){
    Iterator iterator =
    getEntityDef(0).getAllEntityInstancesIterator(getDBTransaction());
    while (iterator.hasNext()) {
    CrsRiskDefinitionsEOImpl test = (CrsRiskDefinitionsEOImpl)iterator.next();
    if (test.getEntityState() == test.STATUS_DELETED) {
    test.revert();
    }
    }
    executeQuery();
    }
}
