package com.novartis.ecrs.model.view;

import oracle.jbo.domain.Number;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Aug 15 19:35:43 IST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CRSVersionCompareVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public CRSVersionCompareVOImpl() {
    }


    /**
     * Returns the variable value for bindEarliestReason.
     * @return variable value for bindEarliestReason
     */
    public String getbindEarliestReason() {
        return (String) ensureVariableManager().getVariableValue("bindEarliestReason");
    }

    /**
     * Sets <code>value</code> for variable bindEarliestReason.
     * @param value value to bind as bindEarliestReason
     */
    public void setbindEarliestReason(String value) {
        ensureVariableManager().setVariableValue("bindEarliestReason", value);
    }

    /**
     * Returns the variable value for bindLatestDate.
     * @return variable value for bindLatestDate
     */
    public String getbindLatestDate() {
        return (String) ensureVariableManager().getVariableValue("bindLatestDate");
    }

    /**
     * Sets <code>value</code> for variable bindLatestDate.
     * @param value value to bind as bindLatestDate
     */
    public void setbindLatestDate(String value) {
        ensureVariableManager().setVariableValue("bindLatestDate", value);
    }

    /**
     * Returns the variable value for bindLatestReason.
     * @return variable value for bindLatestReason
     */
    public String getbindLatestReason() {
        return (String) ensureVariableManager().getVariableValue("bindLatestReason");
    }

    /**
     * Sets <code>value</code> for variable bindLatestReason.
     * @param value value to bind as bindLatestReason
     */
    public void setbindLatestReason(String value) {
        ensureVariableManager().setVariableValue("bindLatestReason", value);
    }

    /**
     * Returns the bind variable value for bindCrsId.
     * @return bind variable value for bindCrsId
     */
    public Integer getbindCrsId() {
        return (Integer) getNamedWhereClauseParam("bindCrsId");
    }

    /**
     * Sets <code>value</code> for bind variable bindCrsId.
     * @param value value to bind as bindCrsId
     */
    public void setbindCrsId(Integer value) {
        setNamedWhereClauseParam("bindCrsId", value);
    }

    /**
     * Returns the bind variable value for bindUserId.
     * @return bind variable value for bindUserId
     */
    public String getbindUserId() {
        return (String) getNamedWhereClauseParam("bindUserId");
    }

    /**
     * Sets <code>value</code> for bind variable bindUserId.
     * @param value value to bind as bindUserId
     */
    public void setbindUserId(String value) {
        setNamedWhereClauseParam("bindUserId", value);
    }

    /**
     * Returns the bind variable value for bindEarliestDate.
     * @return bind variable value for bindEarliestDate
     */
    public String getbindEarliestDate() {
        return (String) getNamedWhereClauseParam("bindEarliestDate");
    }

    /**
     * Sets <code>value</code> for bind variable bindEarliestDate.
     * @param value value to bind as bindEarliestDate
     */
    public void setbindEarliestDate(String value) {
        setNamedWhereClauseParam("bindEarliestDate", value);
    }
}

