package com.novartis.ecrs.model.view;

import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Aug 24 03:14:06 IST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CRSVersionCompareVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        UserId {
            protected Object get(CRSVersionCompareVORowImpl obj) {
                return obj.getUserId();
            }

            protected void put(CRSVersionCompareVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        CrsId {
            protected Object get(CRSVersionCompareVORowImpl obj) {
                return obj.getCrsId();
            }

            protected void put(CRSVersionCompareVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EarliestDate {
            protected Object get(CRSVersionCompareVORowImpl obj) {
                return obj.getEarliestDate();
            }

            protected void put(CRSVersionCompareVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EarliestReason {
            protected Object get(CRSVersionCompareVORowImpl obj) {
                return obj.getEarliestReason();
            }

            protected void put(CRSVersionCompareVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LatestDate {
            protected Object get(CRSVersionCompareVORowImpl obj) {
                return obj.getLatestDate();
            }

            protected void put(CRSVersionCompareVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LatestReason {
            protected Object get(CRSVersionCompareVORowImpl obj) {
                return obj.getLatestReason();
            }

            protected void put(CRSVersionCompareVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EarliestCrsName {
            protected Object get(CRSVersionCompareVORowImpl obj) {
                return obj.getEarliestCrsName();
            }

            protected void put(CRSVersionCompareVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EarliestCrsNameColor {
            protected Object get(CRSVersionCompareVORowImpl obj) {
                return obj.getEarliestCrsNameColor();
            }

            protected void put(CRSVersionCompareVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LatestCrsName {
            protected Object get(CRSVersionCompareVORowImpl obj) {
                return obj.getLatestCrsName();
            }

            protected void put(CRSVersionCompareVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LatestCrsNameColor {
            protected Object get(CRSVersionCompareVORowImpl obj) {
                return obj.getLatestCrsNameColor();
            }

            protected void put(CRSVersionCompareVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EarliestSafetyTopic {
            protected Object get(CRSVersionCompareVORowImpl obj) {
                return obj.getEarliestSafetyTopic();
            }

            protected void put(CRSVersionCompareVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EarliestSafetyTopicColor {
            protected Object get(CRSVersionCompareVORowImpl obj) {
                return obj.getEarliestSafetyTopicColor();
            }

            protected void put(CRSVersionCompareVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EarliestSpp {
            protected Object get(CRSVersionCompareVORowImpl obj) {
                return obj.getEarliestSpp();
            }

            protected void put(CRSVersionCompareVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EarliestDsur {
            protected Object get(CRSVersionCompareVORowImpl obj) {
                return obj.getEarliestDsur();
            }

            protected void put(CRSVersionCompareVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EarliestRmp {
            protected Object get(CRSVersionCompareVORowImpl obj) {
                return obj.getEarliestRmp();
            }

            protected void put(CRSVersionCompareVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EarliestPsur {
            protected Object get(CRSVersionCompareVORowImpl obj) {
                return obj.getEarliestPsur();
            }

            protected void put(CRSVersionCompareVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EarliestIb {
            protected Object get(CRSVersionCompareVORowImpl obj) {
                return obj.getEarliestIb();
            }

            protected void put(CRSVersionCompareVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EarliestCds {
            protected Object get(CRSVersionCompareVORowImpl obj) {
                return obj.getEarliestCds();
            }

            protected void put(CRSVersionCompareVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EarliestOtherSearch {
            protected Object get(CRSVersionCompareVORowImpl obj) {
                return obj.getEarliestOtherSearch();
            }

            protected void put(CRSVersionCompareVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EarliestMissingInformation {
            protected Object get(CRSVersionCompareVORowImpl obj) {
                return obj.getEarliestMissingInformation();
            }

            protected void put(CRSVersionCompareVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EarliestExpeditingRules {
            protected Object get(CRSVersionCompareVORowImpl obj) {
                return obj.getEarliestExpeditingRules();
            }

            protected void put(CRSVersionCompareVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EarliestUnderlyingDisease {
            protected Object get(CRSVersionCompareVORowImpl obj) {
                return obj.getEarliestUnderlyingDisease();
            }

            protected void put(CRSVersionCompareVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EarliestAesiForNisProtcol {
            protected Object get(CRSVersionCompareVORowImpl obj) {
                return obj.getEarliestAesiForNisProtcol();
            }

            protected void put(CRSVersionCompareVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EarliestAesiNotRmp {
            protected Object get(CRSVersionCompareVORowImpl obj) {
                return obj.getEarliestAesiNotRmp();
            }

            protected void put(CRSVersionCompareVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EarliestSppColor {
            protected Object get(CRSVersionCompareVORowImpl obj) {
                return obj.getEarliestSppColor();
            }

            protected void put(CRSVersionCompareVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EarliestDsurColor {
            protected Object get(CRSVersionCompareVORowImpl obj) {
                return obj.getEarliestDsurColor();
            }

            protected void put(CRSVersionCompareVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EarliestRmpColor {
            protected Object get(CRSVersionCompareVORowImpl obj) {
                return obj.getEarliestRmpColor();
            }

            protected void put(CRSVersionCompareVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EarliestPsurColor {
            protected Object get(CRSVersionCompareVORowImpl obj) {
                return obj.getEarliestPsurColor();
            }

            protected void put(CRSVersionCompareVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EarliestIbColor {
            protected Object get(CRSVersionCompareVORowImpl obj) {
                return obj.getEarliestIbColor();
            }

            protected void put(CRSVersionCompareVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EarliestCdsColor {
            protected Object get(CRSVersionCompareVORowImpl obj) {
                return obj.getEarliestCdsColor();
            }

            protected void put(CRSVersionCompareVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EarliestOtherSearchColor {
            protected Object get(CRSVersionCompareVORowImpl obj) {
                return obj.getEarliestOtherSearchColor();
            }

            protected void put(CRSVersionCompareVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EarliestMissingInformColor {
            protected Object get(CRSVersionCompareVORowImpl obj) {
                return obj.getEarliestMissingInformColor();
            }

            protected void put(CRSVersionCompareVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EarliestExpeditingRulColor {
            protected Object get(CRSVersionCompareVORowImpl obj) {
                return obj.getEarliestExpeditingRulColor();
            }

            protected void put(CRSVersionCompareVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EarliestUnderlyingDisColor {
            protected Object get(CRSVersionCompareVORowImpl obj) {
                return obj.getEarliestUnderlyingDisColor();
            }

            protected void put(CRSVersionCompareVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EarliestAesiFrNisProClr {
            protected Object get(CRSVersionCompareVORowImpl obj) {
                return obj.getEarliestAesiFrNisProClr();
            }

            protected void put(CRSVersionCompareVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EarliestAesiNotRmpColor {
            protected Object get(CRSVersionCompareVORowImpl obj) {
                return obj.getEarliestAesiNotRmpColor();
            }

            protected void put(CRSVersionCompareVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EarliestSoc {
            protected Object get(CRSVersionCompareVORowImpl obj) {
                return obj.getEarliestSoc();
            }

            protected void put(CRSVersionCompareVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EarliestSocColor {
            protected Object get(CRSVersionCompareVORowImpl obj) {
                return obj.getEarliestSocColor();
            }

            protected void put(CRSVersionCompareVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EarliestDataDomain {
            protected Object get(CRSVersionCompareVORowImpl obj) {
                return obj.getEarliestDataDomain();
            }

            protected void put(CRSVersionCompareVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EarliestDataDomainColor {
            protected Object get(CRSVersionCompareVORowImpl obj) {
                return obj.getEarliestDataDomainColor();
            }

            protected void put(CRSVersionCompareVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EarliestSearchDetails {
            protected Object get(CRSVersionCompareVORowImpl obj) {
                return obj.getEarliestSearchDetails();
            }

            protected void put(CRSVersionCompareVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EarliestSearchDetailsColor {
            protected Object get(CRSVersionCompareVORowImpl obj) {
                return obj.getEarliestSearchDetailsColor();
            }

            protected void put(CRSVersionCompareVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EarliestMeddraCode {
            protected Object get(CRSVersionCompareVORowImpl obj) {
                return obj.getEarliestMeddraCode();
            }

            protected void put(CRSVersionCompareVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EarliestMeddraCodeColor {
            protected Object get(CRSVersionCompareVORowImpl obj) {
                return obj.getEarliestMeddraCodeColor();
            }

            protected void put(CRSVersionCompareVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EarliestMeddraTerm {
            protected Object get(CRSVersionCompareVORowImpl obj) {
                return obj.getEarliestMeddraTerm();
            }

            protected void put(CRSVersionCompareVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EarliestMeddraTermColor {
            protected Object get(CRSVersionCompareVORowImpl obj) {
                return obj.getEarliestMeddraTermColor();
            }

            protected void put(CRSVersionCompareVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EarliestMeddraExtension {
            protected Object get(CRSVersionCompareVORowImpl obj) {
                return obj.getEarliestMeddraExtension();
            }

            protected void put(CRSVersionCompareVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EarliestMeddraExtColor {
            protected Object get(CRSVersionCompareVORowImpl obj) {
                return obj.getEarliestMeddraExtColor();
            }

            protected void put(CRSVersionCompareVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EarliestMeddraQualifier {
            protected Object get(CRSVersionCompareVORowImpl obj) {
                return obj.getEarliestMeddraQualifier();
            }

            protected void put(CRSVersionCompareVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EarliestMeddraQualColor {
            protected Object get(CRSVersionCompareVORowImpl obj) {
                return obj.getEarliestMeddraQualColor();
            }

            protected void put(CRSVersionCompareVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EarliestNonMeddraCompCmt {
            protected Object get(CRSVersionCompareVORowImpl obj) {
                return obj.getEarliestNonMeddraCompCmt();
            }

            protected void put(CRSVersionCompareVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EarliestNonMedCompCmtClr {
            protected Object get(CRSVersionCompareVORowImpl obj) {
                return obj.getEarliestNonMedCompCmtClr();
            }

            protected void put(CRSVersionCompareVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EarliestMeddraVersionDict {
            protected Object get(CRSVersionCompareVORowImpl obj) {
                return obj.getEarliestMeddraVersionDict();
            }

            protected void put(CRSVersionCompareVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EarliestCrsVersionStrtDate {
            protected Object get(CRSVersionCompareVORowImpl obj) {
                return obj.getEarliestCrsVersionStrtDate();
            }

            protected void put(CRSVersionCompareVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EarliestCrsVersionEndDate {
            protected Object get(CRSVersionCompareVORowImpl obj) {
                return obj.getEarliestCrsVersionEndDate();
            }

            protected void put(CRSVersionCompareVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LatestSafetyTopic {
            protected Object get(CRSVersionCompareVORowImpl obj) {
                return obj.getLatestSafetyTopic();
            }

            protected void put(CRSVersionCompareVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LatestSafetyTopicColor {
            protected Object get(CRSVersionCompareVORowImpl obj) {
                return obj.getLatestSafetyTopicColor();
            }

            protected void put(CRSVersionCompareVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LatestSpp {
            protected Object get(CRSVersionCompareVORowImpl obj) {
                return obj.getLatestSpp();
            }

            protected void put(CRSVersionCompareVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LatestDsur {
            protected Object get(CRSVersionCompareVORowImpl obj) {
                return obj.getLatestDsur();
            }

            protected void put(CRSVersionCompareVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LatestRmp {
            protected Object get(CRSVersionCompareVORowImpl obj) {
                return obj.getLatestRmp();
            }

            protected void put(CRSVersionCompareVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LatestPsur {
            protected Object get(CRSVersionCompareVORowImpl obj) {
                return obj.getLatestPsur();
            }

            protected void put(CRSVersionCompareVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LatestIb {
            protected Object get(CRSVersionCompareVORowImpl obj) {
                return obj.getLatestIb();
            }

            protected void put(CRSVersionCompareVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LatestCds {
            protected Object get(CRSVersionCompareVORowImpl obj) {
                return obj.getLatestCds();
            }

            protected void put(CRSVersionCompareVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LatestOtherSearch {
            protected Object get(CRSVersionCompareVORowImpl obj) {
                return obj.getLatestOtherSearch();
            }

            protected void put(CRSVersionCompareVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LatestMissingInformation {
            protected Object get(CRSVersionCompareVORowImpl obj) {
                return obj.getLatestMissingInformation();
            }

            protected void put(CRSVersionCompareVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LatestExpeditingRules {
            protected Object get(CRSVersionCompareVORowImpl obj) {
                return obj.getLatestExpeditingRules();
            }

            protected void put(CRSVersionCompareVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LatestUnderlyingDisease {
            protected Object get(CRSVersionCompareVORowImpl obj) {
                return obj.getLatestUnderlyingDisease();
            }

            protected void put(CRSVersionCompareVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LatestAesiForNisProtocol {
            protected Object get(CRSVersionCompareVORowImpl obj) {
                return obj.getLatestAesiForNisProtocol();
            }

            protected void put(CRSVersionCompareVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LatestAesiNotRmp {
            protected Object get(CRSVersionCompareVORowImpl obj) {
                return obj.getLatestAesiNotRmp();
            }

            protected void put(CRSVersionCompareVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LatestSppColor {
            protected Object get(CRSVersionCompareVORowImpl obj) {
                return obj.getLatestSppColor();
            }

            protected void put(CRSVersionCompareVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LatestDsurColor {
            protected Object get(CRSVersionCompareVORowImpl obj) {
                return obj.getLatestDsurColor();
            }

            protected void put(CRSVersionCompareVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LatestRmpColor {
            protected Object get(CRSVersionCompareVORowImpl obj) {
                return obj.getLatestRmpColor();
            }

            protected void put(CRSVersionCompareVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LatestPsurColor {
            protected Object get(CRSVersionCompareVORowImpl obj) {
                return obj.getLatestPsurColor();
            }

            protected void put(CRSVersionCompareVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LatestIbColor {
            protected Object get(CRSVersionCompareVORowImpl obj) {
                return obj.getLatestIbColor();
            }

            protected void put(CRSVersionCompareVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LatestCdsColor {
            protected Object get(CRSVersionCompareVORowImpl obj) {
                return obj.getLatestCdsColor();
            }

            protected void put(CRSVersionCompareVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LatestOtherSearchColor {
            protected Object get(CRSVersionCompareVORowImpl obj) {
                return obj.getLatestOtherSearchColor();
            }

            protected void put(CRSVersionCompareVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LatestMissingInfoColor {
            protected Object get(CRSVersionCompareVORowImpl obj) {
                return obj.getLatestMissingInfoColor();
            }

            protected void put(CRSVersionCompareVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LatestExpeditingRulesColor {
            protected Object get(CRSVersionCompareVORowImpl obj) {
                return obj.getLatestExpeditingRulesColor();
            }

            protected void put(CRSVersionCompareVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LatestUnderlyingDisColor {
            protected Object get(CRSVersionCompareVORowImpl obj) {
                return obj.getLatestUnderlyingDisColor();
            }

            protected void put(CRSVersionCompareVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LatestAesiForNisProColor {
            protected Object get(CRSVersionCompareVORowImpl obj) {
                return obj.getLatestAesiForNisProColor();
            }

            protected void put(CRSVersionCompareVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LatestAesiNotRmpColor {
            protected Object get(CRSVersionCompareVORowImpl obj) {
                return obj.getLatestAesiNotRmpColor();
            }

            protected void put(CRSVersionCompareVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LatestSoc {
            protected Object get(CRSVersionCompareVORowImpl obj) {
                return obj.getLatestSoc();
            }

            protected void put(CRSVersionCompareVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LatestSocColor {
            protected Object get(CRSVersionCompareVORowImpl obj) {
                return obj.getLatestSocColor();
            }

            protected void put(CRSVersionCompareVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LatestDataDomain {
            protected Object get(CRSVersionCompareVORowImpl obj) {
                return obj.getLatestDataDomain();
            }

            protected void put(CRSVersionCompareVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LatestDataDomainColor {
            protected Object get(CRSVersionCompareVORowImpl obj) {
                return obj.getLatestDataDomainColor();
            }

            protected void put(CRSVersionCompareVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LatestSearchDetails {
            protected Object get(CRSVersionCompareVORowImpl obj) {
                return obj.getLatestSearchDetails();
            }

            protected void put(CRSVersionCompareVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LatestSearchDetailsColor {
            protected Object get(CRSVersionCompareVORowImpl obj) {
                return obj.getLatestSearchDetailsColor();
            }

            protected void put(CRSVersionCompareVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LatestMeddraCode {
            protected Object get(CRSVersionCompareVORowImpl obj) {
                return obj.getLatestMeddraCode();
            }

            protected void put(CRSVersionCompareVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LatestMeddraCodeColor {
            protected Object get(CRSVersionCompareVORowImpl obj) {
                return obj.getLatestMeddraCodeColor();
            }

            protected void put(CRSVersionCompareVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LatestMeddraTerm {
            protected Object get(CRSVersionCompareVORowImpl obj) {
                return obj.getLatestMeddraTerm();
            }

            protected void put(CRSVersionCompareVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LatestMeddraTermColor {
            protected Object get(CRSVersionCompareVORowImpl obj) {
                return obj.getLatestMeddraTermColor();
            }

            protected void put(CRSVersionCompareVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LatestMeddraExtension {
            protected Object get(CRSVersionCompareVORowImpl obj) {
                return obj.getLatestMeddraExtension();
            }

            protected void put(CRSVersionCompareVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LatestMeddraExtensionColor {
            protected Object get(CRSVersionCompareVORowImpl obj) {
                return obj.getLatestMeddraExtensionColor();
            }

            protected void put(CRSVersionCompareVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LatestMeddraQualifier {
            protected Object get(CRSVersionCompareVORowImpl obj) {
                return obj.getLatestMeddraQualifier();
            }

            protected void put(CRSVersionCompareVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LatestMeddraQualifierColor {
            protected Object get(CRSVersionCompareVORowImpl obj) {
                return obj.getLatestMeddraQualifierColor();
            }

            protected void put(CRSVersionCompareVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LatestNonMeddraCompCmt {
            protected Object get(CRSVersionCompareVORowImpl obj) {
                return obj.getLatestNonMeddraCompCmt();
            }

            protected void put(CRSVersionCompareVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LatestNonMedCompCmtColor {
            protected Object get(CRSVersionCompareVORowImpl obj) {
                return obj.getLatestNonMedCompCmtColor();
            }

            protected void put(CRSVersionCompareVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LatestMedVersionDictionary {
            protected Object get(CRSVersionCompareVORowImpl obj) {
                return obj.getLatestMedVersionDictionary();
            }

            protected void put(CRSVersionCompareVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LatestCrsVersionStartDate {
            protected Object get(CRSVersionCompareVORowImpl obj) {
                return obj.getLatestCrsVersionStartDate();
            }

            protected void put(CRSVersionCompareVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LatestCrsVersionEndDate {
            protected Object get(CRSVersionCompareVORowImpl obj) {
                return obj.getLatestCrsVersionEndDate();
            }

            protected void put(CRSVersionCompareVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EarliestCompound {
            protected Object get(CRSVersionCompareVORowImpl obj) {
                return obj.getEarliestCompound();
            }

            protected void put(CRSVersionCompareVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EarliestCompoundColor {
            protected Object get(CRSVersionCompareVORowImpl obj) {
                return obj.getEarliestCompoundColor();
            }

            protected void put(CRSVersionCompareVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EarliestIndication {
            protected Object get(CRSVersionCompareVORowImpl obj) {
                return obj.getEarliestIndication();
            }

            protected void put(CRSVersionCompareVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EarliestIndicationColor {
            protected Object get(CRSVersionCompareVORowImpl obj) {
                return obj.getEarliestIndicationColor();
            }

            protected void put(CRSVersionCompareVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LatestCompound {
            protected Object get(CRSVersionCompareVORowImpl obj) {
                return obj.getLatestCompound();
            }

            protected void put(CRSVersionCompareVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LatestCompoundColor {
            protected Object get(CRSVersionCompareVORowImpl obj) {
                return obj.getLatestCompoundColor();
            }

            protected void put(CRSVersionCompareVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LatestIndication {
            protected Object get(CRSVersionCompareVORowImpl obj) {
                return obj.getLatestIndication();
            }

            protected void put(CRSVersionCompareVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LatestIndicationColor {
            protected Object get(CRSVersionCompareVORowImpl obj) {
                return obj.getLatestIndicationColor();
            }

            protected void put(CRSVersionCompareVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EarliestSearchAppliedTo {
            protected Object get(CRSVersionCompareVORowImpl obj) {
                return obj.getEarliestSearchAppliedTo();
            }

            protected void put(CRSVersionCompareVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LatestSearchAppliedTo {
            protected Object get(CRSVersionCompareVORowImpl obj) {
                return obj.getLatestSearchAppliedTo();
            }

            protected void put(CRSVersionCompareVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LatestSearchAppliedToColor {
            protected Object get(CRSVersionCompareVORowImpl obj) {
                return obj.getLatestSearchAppliedToColor();
            }

            protected void put(CRSVersionCompareVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EarliestSearchAppliedToClr {
            protected Object get(CRSVersionCompareVORowImpl obj) {
                return obj.getEarliestSearchAppliedToClr();
            }

            protected void put(CRSVersionCompareVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EarliestGender {
            protected Object get(CRSVersionCompareVORowImpl obj) {
                return obj.getEarliestGender();
            }

            protected void put(CRSVersionCompareVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LatestGender {
            protected Object get(CRSVersionCompareVORowImpl obj) {
                return obj.getLatestGender();
            }

            protected void put(CRSVersionCompareVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EarliestGenderCodeColor {
            protected Object get(CRSVersionCompareVORowImpl obj) {
                return obj.getEarliestGenderCodeColor();
            }

            protected void put(CRSVersionCompareVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LatestGenderCodeColor {
            protected Object get(CRSVersionCompareVORowImpl obj) {
                return obj.getLatestGenderCodeColor();
            }

            protected void put(CRSVersionCompareVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EarliestCombAgeSubGrp {
            protected Object get(CRSVersionCompareVORowImpl obj) {
                return obj.getEarliestCombAgeSubGrp();
            }

            protected void put(CRSVersionCompareVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LatestCombAgeSubGrp {
            protected Object get(CRSVersionCompareVORowImpl obj) {
                return obj.getLatestCombAgeSubGrp();
            }

            protected void put(CRSVersionCompareVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EarliestCombAgeSubGrpClr {
            protected Object get(CRSVersionCompareVORowImpl obj) {
                return obj.getEarliestCombAgeSubGrpClr();
            }

            protected void put(CRSVersionCompareVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LatestCombAgeSubGrpClr {
            protected Object get(CRSVersionCompareVORowImpl obj) {
                return obj.getLatestCombAgeSubGrpClr();
            }

            protected void put(CRSVersionCompareVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;


        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }


        protected abstract Object get(CRSVersionCompareVORowImpl object);

        protected abstract void put(CRSVersionCompareVORowImpl object, Object value);
    }


    public static final int USERID = AttributesEnum.UserId.index();
    public static final int CRSID = AttributesEnum.CrsId.index();
    public static final int EARLIESTDATE = AttributesEnum.EarliestDate.index();
    public static final int EARLIESTREASON = AttributesEnum.EarliestReason.index();
    public static final int LATESTDATE = AttributesEnum.LatestDate.index();
    public static final int LATESTREASON = AttributesEnum.LatestReason.index();
    public static final int EARLIESTCRSNAME = AttributesEnum.EarliestCrsName.index();
    public static final int EARLIESTCRSNAMECOLOR = AttributesEnum.EarliestCrsNameColor.index();
    public static final int LATESTCRSNAME = AttributesEnum.LatestCrsName.index();
    public static final int LATESTCRSNAMECOLOR = AttributesEnum.LatestCrsNameColor.index();
    public static final int EARLIESTSAFETYTOPIC = AttributesEnum.EarliestSafetyTopic.index();
    public static final int EARLIESTSAFETYTOPICCOLOR = AttributesEnum.EarliestSafetyTopicColor.index();
    public static final int EARLIESTSPP = AttributesEnum.EarliestSpp.index();
    public static final int EARLIESTDSUR = AttributesEnum.EarliestDsur.index();
    public static final int EARLIESTRMP = AttributesEnum.EarliestRmp.index();
    public static final int EARLIESTPSUR = AttributesEnum.EarliestPsur.index();
    public static final int EARLIESTIB = AttributesEnum.EarliestIb.index();
    public static final int EARLIESTCDS = AttributesEnum.EarliestCds.index();
    public static final int EARLIESTOTHERSEARCH = AttributesEnum.EarliestOtherSearch.index();
    public static final int EARLIESTMISSINGINFORMATION = AttributesEnum.EarliestMissingInformation.index();
    public static final int EARLIESTEXPEDITINGRULES = AttributesEnum.EarliestExpeditingRules.index();
    public static final int EARLIESTUNDERLYINGDISEASE = AttributesEnum.EarliestUnderlyingDisease.index();
    public static final int EARLIESTAESIFORNISPROTCOL = AttributesEnum.EarliestAesiForNisProtcol.index();
    public static final int EARLIESTAESINOTRMP = AttributesEnum.EarliestAesiNotRmp.index();
    public static final int EARLIESTSPPCOLOR = AttributesEnum.EarliestSppColor.index();
    public static final int EARLIESTDSURCOLOR = AttributesEnum.EarliestDsurColor.index();
    public static final int EARLIESTRMPCOLOR = AttributesEnum.EarliestRmpColor.index();
    public static final int EARLIESTPSURCOLOR = AttributesEnum.EarliestPsurColor.index();
    public static final int EARLIESTIBCOLOR = AttributesEnum.EarliestIbColor.index();
    public static final int EARLIESTCDSCOLOR = AttributesEnum.EarliestCdsColor.index();
    public static final int EARLIESTOTHERSEARCHCOLOR = AttributesEnum.EarliestOtherSearchColor.index();
    public static final int EARLIESTMISSINGINFORMCOLOR = AttributesEnum.EarliestMissingInformColor.index();
    public static final int EARLIESTEXPEDITINGRULCOLOR = AttributesEnum.EarliestExpeditingRulColor.index();
    public static final int EARLIESTUNDERLYINGDISCOLOR = AttributesEnum.EarliestUnderlyingDisColor.index();
    public static final int EARLIESTAESIFRNISPROCLR = AttributesEnum.EarliestAesiFrNisProClr.index();
    public static final int EARLIESTAESINOTRMPCOLOR = AttributesEnum.EarliestAesiNotRmpColor.index();
    public static final int EARLIESTSOC = AttributesEnum.EarliestSoc.index();
    public static final int EARLIESTSOCCOLOR = AttributesEnum.EarliestSocColor.index();
    public static final int EARLIESTDATADOMAIN = AttributesEnum.EarliestDataDomain.index();
    public static final int EARLIESTDATADOMAINCOLOR = AttributesEnum.EarliestDataDomainColor.index();
    public static final int EARLIESTSEARCHDETAILS = AttributesEnum.EarliestSearchDetails.index();
    public static final int EARLIESTSEARCHDETAILSCOLOR = AttributesEnum.EarliestSearchDetailsColor.index();
    public static final int EARLIESTMEDDRACODE = AttributesEnum.EarliestMeddraCode.index();
    public static final int EARLIESTMEDDRACODECOLOR = AttributesEnum.EarliestMeddraCodeColor.index();
    public static final int EARLIESTMEDDRATERM = AttributesEnum.EarliestMeddraTerm.index();
    public static final int EARLIESTMEDDRATERMCOLOR = AttributesEnum.EarliestMeddraTermColor.index();
    public static final int EARLIESTMEDDRAEXTENSION = AttributesEnum.EarliestMeddraExtension.index();
    public static final int EARLIESTMEDDRAEXTCOLOR = AttributesEnum.EarliestMeddraExtColor.index();
    public static final int EARLIESTMEDDRAQUALIFIER = AttributesEnum.EarliestMeddraQualifier.index();
    public static final int EARLIESTMEDDRAQUALCOLOR = AttributesEnum.EarliestMeddraQualColor.index();
    public static final int EARLIESTNONMEDDRACOMPCMT = AttributesEnum.EarliestNonMeddraCompCmt.index();
    public static final int EARLIESTNONMEDCOMPCMTCLR = AttributesEnum.EarliestNonMedCompCmtClr.index();
    public static final int EARLIESTMEDDRAVERSIONDICT = AttributesEnum.EarliestMeddraVersionDict.index();
    public static final int EARLIESTCRSVERSIONSTRTDATE = AttributesEnum.EarliestCrsVersionStrtDate.index();
    public static final int EARLIESTCRSVERSIONENDDATE = AttributesEnum.EarliestCrsVersionEndDate.index();
    public static final int LATESTSAFETYTOPIC = AttributesEnum.LatestSafetyTopic.index();
    public static final int LATESTSAFETYTOPICCOLOR = AttributesEnum.LatestSafetyTopicColor.index();
    public static final int LATESTSPP = AttributesEnum.LatestSpp.index();
    public static final int LATESTDSUR = AttributesEnum.LatestDsur.index();
    public static final int LATESTRMP = AttributesEnum.LatestRmp.index();
    public static final int LATESTPSUR = AttributesEnum.LatestPsur.index();
    public static final int LATESTIB = AttributesEnum.LatestIb.index();
    public static final int LATESTCDS = AttributesEnum.LatestCds.index();
    public static final int LATESTOTHERSEARCH = AttributesEnum.LatestOtherSearch.index();
    public static final int LATESTMISSINGINFORMATION = AttributesEnum.LatestMissingInformation.index();
    public static final int LATESTEXPEDITINGRULES = AttributesEnum.LatestExpeditingRules.index();
    public static final int LATESTUNDERLYINGDISEASE = AttributesEnum.LatestUnderlyingDisease.index();
    public static final int LATESTAESIFORNISPROTOCOL = AttributesEnum.LatestAesiForNisProtocol.index();
    public static final int LATESTAESINOTRMP = AttributesEnum.LatestAesiNotRmp.index();
    public static final int LATESTSPPCOLOR = AttributesEnum.LatestSppColor.index();
    public static final int LATESTDSURCOLOR = AttributesEnum.LatestDsurColor.index();
    public static final int LATESTRMPCOLOR = AttributesEnum.LatestRmpColor.index();
    public static final int LATESTPSURCOLOR = AttributesEnum.LatestPsurColor.index();
    public static final int LATESTIBCOLOR = AttributesEnum.LatestIbColor.index();
    public static final int LATESTCDSCOLOR = AttributesEnum.LatestCdsColor.index();
    public static final int LATESTOTHERSEARCHCOLOR = AttributesEnum.LatestOtherSearchColor.index();
    public static final int LATESTMISSINGINFOCOLOR = AttributesEnum.LatestMissingInfoColor.index();
    public static final int LATESTEXPEDITINGRULESCOLOR = AttributesEnum.LatestExpeditingRulesColor.index();
    public static final int LATESTUNDERLYINGDISCOLOR = AttributesEnum.LatestUnderlyingDisColor.index();
    public static final int LATESTAESIFORNISPROCOLOR = AttributesEnum.LatestAesiForNisProColor.index();
    public static final int LATESTAESINOTRMPCOLOR = AttributesEnum.LatestAesiNotRmpColor.index();
    public static final int LATESTSOC = AttributesEnum.LatestSoc.index();
    public static final int LATESTSOCCOLOR = AttributesEnum.LatestSocColor.index();
    public static final int LATESTDATADOMAIN = AttributesEnum.LatestDataDomain.index();
    public static final int LATESTDATADOMAINCOLOR = AttributesEnum.LatestDataDomainColor.index();
    public static final int LATESTSEARCHDETAILS = AttributesEnum.LatestSearchDetails.index();
    public static final int LATESTSEARCHDETAILSCOLOR = AttributesEnum.LatestSearchDetailsColor.index();
    public static final int LATESTMEDDRACODE = AttributesEnum.LatestMeddraCode.index();
    public static final int LATESTMEDDRACODECOLOR = AttributesEnum.LatestMeddraCodeColor.index();
    public static final int LATESTMEDDRATERM = AttributesEnum.LatestMeddraTerm.index();
    public static final int LATESTMEDDRATERMCOLOR = AttributesEnum.LatestMeddraTermColor.index();
    public static final int LATESTMEDDRAEXTENSION = AttributesEnum.LatestMeddraExtension.index();
    public static final int LATESTMEDDRAEXTENSIONCOLOR = AttributesEnum.LatestMeddraExtensionColor.index();
    public static final int LATESTMEDDRAQUALIFIER = AttributesEnum.LatestMeddraQualifier.index();
    public static final int LATESTMEDDRAQUALIFIERCOLOR = AttributesEnum.LatestMeddraQualifierColor.index();
    public static final int LATESTNONMEDDRACOMPCMT = AttributesEnum.LatestNonMeddraCompCmt.index();
    public static final int LATESTNONMEDCOMPCMTCOLOR = AttributesEnum.LatestNonMedCompCmtColor.index();
    public static final int LATESTMEDVERSIONDICTIONARY = AttributesEnum.LatestMedVersionDictionary.index();
    public static final int LATESTCRSVERSIONSTARTDATE = AttributesEnum.LatestCrsVersionStartDate.index();
    public static final int LATESTCRSVERSIONENDDATE = AttributesEnum.LatestCrsVersionEndDate.index();
    public static final int EARLIESTCOMPOUND = AttributesEnum.EarliestCompound.index();
    public static final int EARLIESTCOMPOUNDCOLOR = AttributesEnum.EarliestCompoundColor.index();
    public static final int EARLIESTINDICATION = AttributesEnum.EarliestIndication.index();
    public static final int EARLIESTINDICATIONCOLOR = AttributesEnum.EarliestIndicationColor.index();
    public static final int LATESTCOMPOUND = AttributesEnum.LatestCompound.index();
    public static final int LATESTCOMPOUNDCOLOR = AttributesEnum.LatestCompoundColor.index();
    public static final int LATESTINDICATION = AttributesEnum.LatestIndication.index();
    public static final int LATESTINDICATIONCOLOR = AttributesEnum.LatestIndicationColor.index();
    public static final int EARLIESTSEARCHAPPLIEDTO = AttributesEnum.EarliestSearchAppliedTo.index();
    public static final int LATESTSEARCHAPPLIEDTO = AttributesEnum.LatestSearchAppliedTo.index();
    public static final int LATESTSEARCHAPPLIEDTOCOLOR = AttributesEnum.LatestSearchAppliedToColor.index();
    public static final int EARLIESTSEARCHAPPLIEDTOCLR = AttributesEnum.EarliestSearchAppliedToClr.index();
    public static final int EARLIESTGENDER = AttributesEnum.EarliestGender.index();
    public static final int LATESTGENDER = AttributesEnum.LatestGender.index();
    public static final int EARLIESTGENDERCODECOLOR = AttributesEnum.EarliestGenderCodeColor.index();
    public static final int LATESTGENDERCODECOLOR = AttributesEnum.LatestGenderCodeColor.index();
    public static final int EARLIESTCOMBAGESUBGRP = AttributesEnum.EarliestCombAgeSubGrp.index();
    public static final int LATESTCOMBAGESUBGRP = AttributesEnum.LatestCombAgeSubGrp.index();
    public static final int EARLIESTCOMBAGESUBGRPCLR = AttributesEnum.EarliestCombAgeSubGrpClr.index();
    public static final int LATESTCOMBAGESUBGRPCLR = AttributesEnum.LatestCombAgeSubGrpClr.index();

    /**
     * This is the default constructor (do not remove).
     */
    public CRSVersionCompareVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute UserId.
     * @return the UserId
     */
    public String getUserId() {
        return (String) getAttributeInternal(USERID);
    }

    /**
     * Gets the attribute value for the calculated attribute CrsId.
     * @return the CrsId
     */
    public Integer getCrsId() {
        return (Integer) getAttributeInternal(CRSID);
    }

    /**
     * Gets the attribute value for the calculated attribute EarliestDate.
     * @return the EarliestDate
     */
    public String getEarliestDate() {
        return (String) getAttributeInternal(EARLIESTDATE);
    }

    /**
     * Gets the attribute value for the calculated attribute EarliestReason.
     * @return the EarliestReason
     */
    public String getEarliestReason() {
        return (String) getAttributeInternal(EARLIESTREASON);
    }

    /**
     * Gets the attribute value for the calculated attribute LatestDate.
     * @return the LatestDate
     */
    public String getLatestDate() {
        return (String) getAttributeInternal(LATESTDATE);
    }

    /**
     * Gets the attribute value for the calculated attribute LatestReason.
     * @return the LatestReason
     */
    public String getLatestReason() {
        return (String) getAttributeInternal(LATESTREASON);
    }

    /**
     * Gets the attribute value for the calculated attribute EarliestCrsName.
     * @return the EarliestCrsName
     */
    public String getEarliestCrsName() {
        return (String) getAttributeInternal(EARLIESTCRSNAME);
    }

    /**
     * Gets the attribute value for the calculated attribute EarliestCrsNameColor.
     * @return the EarliestCrsNameColor
     */
    public String getEarliestCrsNameColor() {
        return (String) getAttributeInternal(EARLIESTCRSNAMECOLOR);
    }

    /**
     * Gets the attribute value for the calculated attribute LatestCrsName.
     * @return the LatestCrsName
     */
    public String getLatestCrsName() {
        return (String) getAttributeInternal(LATESTCRSNAME);
    }

    /**
     * Gets the attribute value for the calculated attribute LatestCrsNameColor.
     * @return the LatestCrsNameColor
     */
    public String getLatestCrsNameColor() {
        return (String) getAttributeInternal(LATESTCRSNAMECOLOR);
    }

    /**
     * Gets the attribute value for the calculated attribute EarliestSafetyTopic.
     * @return the EarliestSafetyTopic
     */
    public String getEarliestSafetyTopic() {
        return (String) getAttributeInternal(EARLIESTSAFETYTOPIC);
    }

    /**
     * Gets the attribute value for the calculated attribute EarliestSafetyTopicColor.
     * @return the EarliestSafetyTopicColor
     */
    public String getEarliestSafetyTopicColor() {
        return (String) getAttributeInternal(EARLIESTSAFETYTOPICCOLOR);
    }

    /**
     * Gets the attribute value for the calculated attribute EarliestSpp.
     * @return the EarliestSpp
     */
    public String getEarliestSpp() {
        return (String) getAttributeInternal(EARLIESTSPP);
    }

    /**
     * Gets the attribute value for the calculated attribute EarliestDsur.
     * @return the EarliestDsur
     */
    public String getEarliestDsur() {
        return (String) getAttributeInternal(EARLIESTDSUR);
    }

    /**
     * Gets the attribute value for the calculated attribute EarliestRmp.
     * @return the EarliestRmp
     */
    public String getEarliestRmp() {
        return (String) getAttributeInternal(EARLIESTRMP);
    }

    /**
     * Gets the attribute value for the calculated attribute EarliestPsur.
     * @return the EarliestPsur
     */
    public String getEarliestPsur() {
        return (String) getAttributeInternal(EARLIESTPSUR);
    }

    /**
     * Gets the attribute value for the calculated attribute EarliestIb.
     * @return the EarliestIb
     */
    public String getEarliestIb() {
        return (String) getAttributeInternal(EARLIESTIB);
    }

    /**
     * Gets the attribute value for the calculated attribute EarliestCds.
     * @return the EarliestCds
     */
    public String getEarliestCds() {
        return (String) getAttributeInternal(EARLIESTCDS);
    }

    /**
     * Gets the attribute value for the calculated attribute EarliestOtherSearch.
     * @return the EarliestOtherSearch
     */
    public String getEarliestOtherSearch() {
        return (String) getAttributeInternal(EARLIESTOTHERSEARCH);
    }

    /**
     * Gets the attribute value for the calculated attribute EarliestMissingInformation.
     * @return the EarliestMissingInformation
     */
    public String getEarliestMissingInformation() {
        return (String) getAttributeInternal(EARLIESTMISSINGINFORMATION);
    }

    /**
     * Gets the attribute value for the calculated attribute EarliestExpeditingRules.
     * @return the EarliestExpeditingRules
     */
    public String getEarliestExpeditingRules() {
        return (String) getAttributeInternal(EARLIESTEXPEDITINGRULES);
    }

    /**
     * Gets the attribute value for the calculated attribute EarliestUnderlyingDisease.
     * @return the EarliestUnderlyingDisease
     */
    public String getEarliestUnderlyingDisease() {
        return (String) getAttributeInternal(EARLIESTUNDERLYINGDISEASE);
    }

    /**
     * Gets the attribute value for the calculated attribute EarliestAesiForNisProtcol.
     * @return the EarliestAesiForNisProtcol
     */
    public String getEarliestAesiForNisProtcol() {
        return (String) getAttributeInternal(EARLIESTAESIFORNISPROTCOL);
    }

    /**
     * Gets the attribute value for the calculated attribute EarliestAesiNotRmp.
     * @return the EarliestAesiNotRmp
     */
    public String getEarliestAesiNotRmp() {
        return (String) getAttributeInternal(EARLIESTAESINOTRMP);
    }

    /**
     * Gets the attribute value for the calculated attribute EarliestSppColor.
     * @return the EarliestSppColor
     */
    public String getEarliestSppColor() {
        return (String) getAttributeInternal(EARLIESTSPPCOLOR);
    }

    /**
     * Gets the attribute value for the calculated attribute EarliestDsurColor.
     * @return the EarliestDsurColor
     */
    public String getEarliestDsurColor() {
        return (String) getAttributeInternal(EARLIESTDSURCOLOR);
    }

    /**
     * Gets the attribute value for the calculated attribute EarliestRmpColor.
     * @return the EarliestRmpColor
     */
    public String getEarliestRmpColor() {
        return (String) getAttributeInternal(EARLIESTRMPCOLOR);
    }

    /**
     * Gets the attribute value for the calculated attribute EarliestPsurColor.
     * @return the EarliestPsurColor
     */
    public String getEarliestPsurColor() {
        return (String) getAttributeInternal(EARLIESTPSURCOLOR);
    }

    /**
     * Gets the attribute value for the calculated attribute EarliestIbColor.
     * @return the EarliestIbColor
     */
    public String getEarliestIbColor() {
        return (String) getAttributeInternal(EARLIESTIBCOLOR);
    }

    /**
     * Gets the attribute value for the calculated attribute EarliestCdsColor.
     * @return the EarliestCdsColor
     */
    public String getEarliestCdsColor() {
        return (String) getAttributeInternal(EARLIESTCDSCOLOR);
    }

    /**
     * Gets the attribute value for the calculated attribute EarliestOtherSearchColor.
     * @return the EarliestOtherSearchColor
     */
    public String getEarliestOtherSearchColor() {
        return (String) getAttributeInternal(EARLIESTOTHERSEARCHCOLOR);
    }

    /**
     * Gets the attribute value for the calculated attribute EarliestMissingInformColor.
     * @return the EarliestMissingInformColor
     */
    public String getEarliestMissingInformColor() {
        return (String) getAttributeInternal(EARLIESTMISSINGINFORMCOLOR);
    }

    /**
     * Gets the attribute value for the calculated attribute EarliestExpeditingRulColor.
     * @return the EarliestExpeditingRulColor
     */
    public String getEarliestExpeditingRulColor() {
        return (String) getAttributeInternal(EARLIESTEXPEDITINGRULCOLOR);
    }

    /**
     * Gets the attribute value for the calculated attribute EarliestUnderlyingDisColor.
     * @return the EarliestUnderlyingDisColor
     */
    public String getEarliestUnderlyingDisColor() {
        return (String) getAttributeInternal(EARLIESTUNDERLYINGDISCOLOR);
    }

    /**
     * Gets the attribute value for the calculated attribute EarliestAesiFrNisProClr.
     * @return the EarliestAesiFrNisProClr
     */
    public String getEarliestAesiFrNisProClr() {
        return (String) getAttributeInternal(EARLIESTAESIFRNISPROCLR);
    }

    /**
     * Gets the attribute value for the calculated attribute EarliestAesiNotRmpColor.
     * @return the EarliestAesiNotRmpColor
     */
    public String getEarliestAesiNotRmpColor() {
        return (String) getAttributeInternal(EARLIESTAESINOTRMPCOLOR);
    }

    /**
     * Gets the attribute value for the calculated attribute EarliestSoc.
     * @return the EarliestSoc
     */
    public String getEarliestSoc() {
        return (String) getAttributeInternal(EARLIESTSOC);
    }

    /**
     * Gets the attribute value for the calculated attribute EarliestSocColor.
     * @return the EarliestSocColor
     */
    public String getEarliestSocColor() {
        return (String) getAttributeInternal(EARLIESTSOCCOLOR);
    }

    /**
     * Gets the attribute value for the calculated attribute EarliestDataDomain.
     * @return the EarliestDataDomain
     */
    public String getEarliestDataDomain() {
        return (String) getAttributeInternal(EARLIESTDATADOMAIN);
    }

    /**
     * Gets the attribute value for the calculated attribute EarliestDataDomainColor.
     * @return the EarliestDataDomainColor
     */
    public String getEarliestDataDomainColor() {
        return (String) getAttributeInternal(EARLIESTDATADOMAINCOLOR);
    }

    /**
     * Gets the attribute value for the calculated attribute EarliestSearchDetails.
     * @return the EarliestSearchDetails
     */
    public String getEarliestSearchDetails() {
        return (String) getAttributeInternal(EARLIESTSEARCHDETAILS);
    }

    /**
     * Gets the attribute value for the calculated attribute EarliestSearchDetailsColor.
     * @return the EarliestSearchDetailsColor
     */
    public String getEarliestSearchDetailsColor() {
        return (String) getAttributeInternal(EARLIESTSEARCHDETAILSCOLOR);
    }

    /**
     * Gets the attribute value for the calculated attribute EarliestMeddraCode.
     * @return the EarliestMeddraCode
     */
    public Integer getEarliestMeddraCode() {
        return (Integer) getAttributeInternal(EARLIESTMEDDRACODE);
    }

    /**
     * Gets the attribute value for the calculated attribute EarliestMeddraCodeColor.
     * @return the EarliestMeddraCodeColor
     */
    public String getEarliestMeddraCodeColor() {
        return (String) getAttributeInternal(EARLIESTMEDDRACODECOLOR);
    }

    /**
     * Gets the attribute value for the calculated attribute EarliestMeddraTerm.
     * @return the EarliestMeddraTerm
     */
    public String getEarliestMeddraTerm() {
        return (String) getAttributeInternal(EARLIESTMEDDRATERM);
    }

    /**
     * Gets the attribute value for the calculated attribute EarliestMeddraTermColor.
     * @return the EarliestMeddraTermColor
     */
    public String getEarliestMeddraTermColor() {
        return (String) getAttributeInternal(EARLIESTMEDDRATERMCOLOR);
    }

    /**
     * Gets the attribute value for the calculated attribute EarliestMeddraExtension.
     * @return the EarliestMeddraExtension
     */
    public String getEarliestMeddraExtension() {
        return (String) getAttributeInternal(EARLIESTMEDDRAEXTENSION);
    }

    /**
     * Gets the attribute value for the calculated attribute EarliestMeddraExtColor.
     * @return the EarliestMeddraExtColor
     */
    public String getEarliestMeddraExtColor() {
        return (String) getAttributeInternal(EARLIESTMEDDRAEXTCOLOR);
    }

    /**
     * Gets the attribute value for the calculated attribute EarliestMeddraQualifier.
     * @return the EarliestMeddraQualifier
     */
    public String getEarliestMeddraQualifier() {
        return (String) getAttributeInternal(EARLIESTMEDDRAQUALIFIER);
    }

    /**
     * Gets the attribute value for the calculated attribute EarliestMeddraQualColor.
     * @return the EarliestMeddraQualColor
     */
    public String getEarliestMeddraQualColor() {
        return (String) getAttributeInternal(EARLIESTMEDDRAQUALCOLOR);
    }

    /**
     * Gets the attribute value for the calculated attribute EarliestNonMeddraCompCmt.
     * @return the EarliestNonMeddraCompCmt
     */
    public String getEarliestNonMeddraCompCmt() {
        return (String) getAttributeInternal(EARLIESTNONMEDDRACOMPCMT);
    }

    /**
     * Gets the attribute value for the calculated attribute EarliestNonMedCompCmtClr.
     * @return the EarliestNonMedCompCmtClr
     */
    public String getEarliestNonMedCompCmtClr() {
        return (String) getAttributeInternal(EARLIESTNONMEDCOMPCMTCLR);
    }

    /**
     * Gets the attribute value for the calculated attribute EarliestMeddraVersionDict.
     * @return the EarliestMeddraVersionDict
     */
    public String getEarliestMeddraVersionDict() {
        return (String) getAttributeInternal(EARLIESTMEDDRAVERSIONDICT);
    }

    /**
     * Gets the attribute value for the calculated attribute EarliestCrsVersionStrtDate.
     * @return the EarliestCrsVersionStrtDate
     */
    public String getEarliestCrsVersionStrtDate() {
        return (String) getAttributeInternal(EARLIESTCRSVERSIONSTRTDATE);
    }

    /**
     * Gets the attribute value for the calculated attribute EarliestCrsVersionEndDate.
     * @return the EarliestCrsVersionEndDate
     */
    public String getEarliestCrsVersionEndDate() {
        return (String) getAttributeInternal(EARLIESTCRSVERSIONENDDATE);
    }

    /**
     * Gets the attribute value for the calculated attribute LatestSafetyTopic.
     * @return the LatestSafetyTopic
     */
    public String getLatestSafetyTopic() {
        return (String) getAttributeInternal(LATESTSAFETYTOPIC);
    }

    /**
     * Gets the attribute value for the calculated attribute LatestSafetyTopicColor.
     * @return the LatestSafetyTopicColor
     */
    public String getLatestSafetyTopicColor() {
        return (String) getAttributeInternal(LATESTSAFETYTOPICCOLOR);
    }

    /**
     * Gets the attribute value for the calculated attribute LatestSpp.
     * @return the LatestSpp
     */
    public String getLatestSpp() {
        return (String) getAttributeInternal(LATESTSPP);
    }

    /**
     * Gets the attribute value for the calculated attribute LatestDsur.
     * @return the LatestDsur
     */
    public String getLatestDsur() {
        return (String) getAttributeInternal(LATESTDSUR);
    }

    /**
     * Gets the attribute value for the calculated attribute LatestRmp.
     * @return the LatestRmp
     */
    public String getLatestRmp() {
        return (String) getAttributeInternal(LATESTRMP);
    }

    /**
     * Gets the attribute value for the calculated attribute LatestPsur.
     * @return the LatestPsur
     */
    public String getLatestPsur() {
        return (String) getAttributeInternal(LATESTPSUR);
    }

    /**
     * Gets the attribute value for the calculated attribute LatestIb.
     * @return the LatestIb
     */
    public String getLatestIb() {
        return (String) getAttributeInternal(LATESTIB);
    }

    /**
     * Gets the attribute value for the calculated attribute LatestCds.
     * @return the LatestCds
     */
    public String getLatestCds() {
        return (String) getAttributeInternal(LATESTCDS);
    }

    /**
     * Gets the attribute value for the calculated attribute LatestOtherSearch.
     * @return the LatestOtherSearch
     */
    public String getLatestOtherSearch() {
        return (String) getAttributeInternal(LATESTOTHERSEARCH);
    }

    /**
     * Gets the attribute value for the calculated attribute LatestMissingInformation.
     * @return the LatestMissingInformation
     */
    public String getLatestMissingInformation() {
        return (String) getAttributeInternal(LATESTMISSINGINFORMATION);
    }

    /**
     * Gets the attribute value for the calculated attribute LatestExpeditingRules.
     * @return the LatestExpeditingRules
     */
    public String getLatestExpeditingRules() {
        return (String) getAttributeInternal(LATESTEXPEDITINGRULES);
    }

    /**
     * Gets the attribute value for the calculated attribute LatestUnderlyingDisease.
     * @return the LatestUnderlyingDisease
     */
    public String getLatestUnderlyingDisease() {
        return (String) getAttributeInternal(LATESTUNDERLYINGDISEASE);
    }

    /**
     * Gets the attribute value for the calculated attribute LatestAesiForNisProtocol.
     * @return the LatestAesiForNisProtocol
     */
    public String getLatestAesiForNisProtocol() {
        return (String) getAttributeInternal(LATESTAESIFORNISPROTOCOL);
    }

    /**
     * Gets the attribute value for the calculated attribute LatestAesiNotRmp.
     * @return the LatestAesiNotRmp
     */
    public String getLatestAesiNotRmp() {
        return (String) getAttributeInternal(LATESTAESINOTRMP);
    }

    /**
     * Gets the attribute value for the calculated attribute LatestSppColor.
     * @return the LatestSppColor
     */
    public String getLatestSppColor() {
        return (String) getAttributeInternal(LATESTSPPCOLOR);
    }

    /**
     * Gets the attribute value for the calculated attribute LatestDsurColor.
     * @return the LatestDsurColor
     */
    public String getLatestDsurColor() {
        return (String) getAttributeInternal(LATESTDSURCOLOR);
    }

    /**
     * Gets the attribute value for the calculated attribute LatestRmpColor.
     * @return the LatestRmpColor
     */
    public String getLatestRmpColor() {
        return (String) getAttributeInternal(LATESTRMPCOLOR);
    }

    /**
     * Gets the attribute value for the calculated attribute LatestPsurColor.
     * @return the LatestPsurColor
     */
    public String getLatestPsurColor() {
        return (String) getAttributeInternal(LATESTPSURCOLOR);
    }

    /**
     * Gets the attribute value for the calculated attribute LatestIbColor.
     * @return the LatestIbColor
     */
    public String getLatestIbColor() {
        return (String) getAttributeInternal(LATESTIBCOLOR);
    }

    /**
     * Gets the attribute value for the calculated attribute LatestCdsColor.
     * @return the LatestCdsColor
     */
    public String getLatestCdsColor() {
        return (String) getAttributeInternal(LATESTCDSCOLOR);
    }

    /**
     * Gets the attribute value for the calculated attribute LatestOtherSearchColor.
     * @return the LatestOtherSearchColor
     */
    public String getLatestOtherSearchColor() {
        return (String) getAttributeInternal(LATESTOTHERSEARCHCOLOR);
    }

    /**
     * Gets the attribute value for the calculated attribute LatestMissingInfoColor.
     * @return the LatestMissingInfoColor
     */
    public String getLatestMissingInfoColor() {
        return (String) getAttributeInternal(LATESTMISSINGINFOCOLOR);
    }

    /**
     * Gets the attribute value for the calculated attribute LatestExpeditingRulesColor.
     * @return the LatestExpeditingRulesColor
     */
    public String getLatestExpeditingRulesColor() {
        return (String) getAttributeInternal(LATESTEXPEDITINGRULESCOLOR);
    }

    /**
     * Gets the attribute value for the calculated attribute LatestUnderlyingDisColor.
     * @return the LatestUnderlyingDisColor
     */
    public String getLatestUnderlyingDisColor() {
        return (String) getAttributeInternal(LATESTUNDERLYINGDISCOLOR);
    }

    /**
     * Gets the attribute value for the calculated attribute LatestAesiForNisProColor.
     * @return the LatestAesiForNisProColor
     */
    public String getLatestAesiForNisProColor() {
        return (String) getAttributeInternal(LATESTAESIFORNISPROCOLOR);
    }

    /**
     * Gets the attribute value for the calculated attribute LatestAesiNotRmpColor.
     * @return the LatestAesiNotRmpColor
     */
    public String getLatestAesiNotRmpColor() {
        return (String) getAttributeInternal(LATESTAESINOTRMPCOLOR);
    }

    /**
     * Gets the attribute value for the calculated attribute LatestSoc.
     * @return the LatestSoc
     */
    public String getLatestSoc() {
        return (String) getAttributeInternal(LATESTSOC);
    }

    /**
     * Gets the attribute value for the calculated attribute LatestSocColor.
     * @return the LatestSocColor
     */
    public String getLatestSocColor() {
        return (String) getAttributeInternal(LATESTSOCCOLOR);
    }

    /**
     * Gets the attribute value for the calculated attribute LatestDataDomain.
     * @return the LatestDataDomain
     */
    public String getLatestDataDomain() {
        return (String) getAttributeInternal(LATESTDATADOMAIN);
    }


    /**
     * Gets the attribute value for the calculated attribute LatestDataDomainColor.
     * @return the LatestDataDomainColor
     */
    public String getLatestDataDomainColor() {
        return (String) getAttributeInternal(LATESTDATADOMAINCOLOR);
    }

    /**
     * Gets the attribute value for the calculated attribute LatestSearchDetails.
     * @return the LatestSearchDetails
     */
    public String getLatestSearchDetails() {
        return (String) getAttributeInternal(LATESTSEARCHDETAILS);
    }

    /**
     * Gets the attribute value for the calculated attribute LatestSearchDetailsColor.
     * @return the LatestSearchDetailsColor
     */
    public String getLatestSearchDetailsColor() {
        return (String) getAttributeInternal(LATESTSEARCHDETAILSCOLOR);
    }

    /**
     * Gets the attribute value for the calculated attribute LatestMeddraCode.
     * @return the LatestMeddraCode
     */
    public Integer getLatestMeddraCode() {
        return (Integer) getAttributeInternal(LATESTMEDDRACODE);
    }

    /**
     * Gets the attribute value for the calculated attribute LatestMeddraCodeColor.
     * @return the LatestMeddraCodeColor
     */
    public String getLatestMeddraCodeColor() {
        return (String) getAttributeInternal(LATESTMEDDRACODECOLOR);
    }

    /**
     * Gets the attribute value for the calculated attribute LatestMeddraTerm.
     * @return the LatestMeddraTerm
     */
    public String getLatestMeddraTerm() {
        return (String) getAttributeInternal(LATESTMEDDRATERM);
    }

    /**
     * Gets the attribute value for the calculated attribute LatestMeddraTermColor.
     * @return the LatestMeddraTermColor
     */
    public String getLatestMeddraTermColor() {
        return (String) getAttributeInternal(LATESTMEDDRATERMCOLOR);
    }

    /**
     * Gets the attribute value for the calculated attribute LatestMeddraExtension.
     * @return the LatestMeddraExtension
     */
    public String getLatestMeddraExtension() {
        return (String) getAttributeInternal(LATESTMEDDRAEXTENSION);
    }

    /**
     * Gets the attribute value for the calculated attribute LatestMeddraExtensionColor.
     * @return the LatestMeddraExtensionColor
     */
    public String getLatestMeddraExtensionColor() {
        return (String) getAttributeInternal(LATESTMEDDRAEXTENSIONCOLOR);
    }

    /**
     * Gets the attribute value for the calculated attribute LatestMeddraQualifier.
     * @return the LatestMeddraQualifier
     */
    public String getLatestMeddraQualifier() {
        return (String) getAttributeInternal(LATESTMEDDRAQUALIFIER);
    }

    /**
     * Gets the attribute value for the calculated attribute LatestMeddraQualifierColor.
     * @return the LatestMeddraQualifierColor
     */
    public String getLatestMeddraQualifierColor() {
        return (String) getAttributeInternal(LATESTMEDDRAQUALIFIERCOLOR);
    }

    /**
     * Gets the attribute value for the calculated attribute LatestNonMeddraCompCmt.
     * @return the LatestNonMeddraCompCmt
     */
    public String getLatestNonMeddraCompCmt() {
        return (String) getAttributeInternal(LATESTNONMEDDRACOMPCMT);
    }

    /**
     * Gets the attribute value for the calculated attribute LatestNonMedCompCmtColor.
     * @return the LatestNonMedCompCmtColor
     */
    public String getLatestNonMedCompCmtColor() {
        return (String) getAttributeInternal(LATESTNONMEDCOMPCMTCOLOR);
    }

    /**
     * Gets the attribute value for the calculated attribute LatestMedVersionDictionary.
     * @return the LatestMedVersionDictionary
     */
    public String getLatestMedVersionDictionary() {
        return (String) getAttributeInternal(LATESTMEDVERSIONDICTIONARY);
    }

    /**
     * Gets the attribute value for the calculated attribute LatestCrsVersionStartDate.
     * @return the LatestCrsVersionStartDate
     */
    public String getLatestCrsVersionStartDate() {
        return (String) getAttributeInternal(LATESTCRSVERSIONSTARTDATE);
    }

    /**
     * Gets the attribute value for the calculated attribute LatestCrsVersionEndDate.
     * @return the LatestCrsVersionEndDate
     */
    public String getLatestCrsVersionEndDate() {
        return (String) getAttributeInternal(LATESTCRSVERSIONENDDATE);
    }

    /**
     * Gets the attribute value for the calculated attribute EarliestCompound.
     * @return the EarliestCompound
     */
    public String getEarliestCompound() {
        return (String) getAttributeInternal(EARLIESTCOMPOUND);
    }

    /**
     * Gets the attribute value for the calculated attribute EarliestCompoundColor.
     * @return the EarliestCompoundColor
     */
    public String getEarliestCompoundColor() {
        return (String) getAttributeInternal(EARLIESTCOMPOUNDCOLOR);
    }

    /**
     * Gets the attribute value for the calculated attribute EarliestIndication.
     * @return the EarliestIndication
     */
    public String getEarliestIndication() {
        return (String) getAttributeInternal(EARLIESTINDICATION);
    }

    /**
     * Gets the attribute value for the calculated attribute EarliestIndicationColor.
     * @return the EarliestIndicationColor
     */
    public String getEarliestIndicationColor() {
        return (String) getAttributeInternal(EARLIESTINDICATIONCOLOR);
    }

    /**
     * Gets the attribute value for the calculated attribute LatestCompound.
     * @return the LatestCompound
     */
    public String getLatestCompound() {
        return (String) getAttributeInternal(LATESTCOMPOUND);
    }

    /**
     * Gets the attribute value for the calculated attribute LatestCompoundColor.
     * @return the LatestCompoundColor
     */
    public String getLatestCompoundColor() {
        return (String) getAttributeInternal(LATESTCOMPOUNDCOLOR);
    }

    /**
     * Gets the attribute value for the calculated attribute LatestIndication.
     * @return the LatestIndication
     */
    public String getLatestIndication() {
        return (String) getAttributeInternal(LATESTINDICATION);
    }

    /**
     * Gets the attribute value for the calculated attribute LatestIndicationColor.
     * @return the LatestIndicationColor
     */
    public String getLatestIndicationColor() {
        return (String) getAttributeInternal(LATESTINDICATIONCOLOR);
    }


    /**
     * Gets the attribute value for the calculated attribute EarliestSearchAppliedTo.
     * @return the EarliestSearchAppliedTo
     */
    public String getEarliestSearchAppliedTo() {
        return (String) getAttributeInternal(EARLIESTSEARCHAPPLIEDTO);
    }

    /**
     * Gets the attribute value for the calculated attribute LatestSearchAppliedTo.
     * @return the LatestSearchAppliedTo
     */
    public String getLatestSearchAppliedTo() {
        return (String) getAttributeInternal(LATESTSEARCHAPPLIEDTO);
    }

    /**
     * Gets the attribute value for the calculated attribute LatestSearchAppliedToColor.
     * @return the LatestSearchAppliedToColor
     */
    public String getLatestSearchAppliedToColor() {
        return (String) getAttributeInternal(LATESTSEARCHAPPLIEDTOCOLOR);
    }

    /**
     * Gets the attribute value for the calculated attribute EarliestSearchAppliedToClr.
     * @return the EarliestSearchAppliedToClr
     */
    public String getEarliestSearchAppliedToClr() {
        return (String) getAttributeInternal(EARLIESTSEARCHAPPLIEDTOCLR);
    }

    /**
     * Gets the attribute value for the calculated attribute EarliestGender.
     * @return the EarliestGender
     */
    public String getEarliestGender() {
        return (String) getAttributeInternal(EARLIESTGENDER);
    }

    /**
     * Gets the attribute value for the calculated attribute LatestGender.
     * @return the LatestGender
     */
    public String getLatestGender() {
        return (String) getAttributeInternal(LATESTGENDER);
    }

    /**
     * Gets the attribute value for the calculated attribute EarliestGenderCodeColor.
     * @return the EarliestGenderCodeColor
     */
    public String getEarliestGenderCodeColor() {
        return (String) getAttributeInternal(EARLIESTGENDERCODECOLOR);
    }

    /**
     * Gets the attribute value for the calculated attribute LatestGenderCodeColor.
     * @return the LatestGenderCodeColor
     */
    public String getLatestGenderCodeColor() {
        return (String) getAttributeInternal(LATESTGENDERCODECOLOR);
    }

    /**
     * Gets the attribute value for the calculated attribute EarliestCombAgeSubGrp.
     * @return the EarliestCombAgeSubGrp
     */
    public String getEarliestCombAgeSubGrp() {
        return (String) getAttributeInternal(EARLIESTCOMBAGESUBGRP);
    }

    /**
     * Gets the attribute value for the calculated attribute LatestCombAgeSubGrp.
     * @return the LatestCombAgeSubGrp
     */
    public String getLatestCombAgeSubGrp() {
        return (String) getAttributeInternal(LATESTCOMBAGESUBGRP);
    }

    /**
     * Gets the attribute value for the calculated attribute EarliestCombAgeSubGrpClr.
     * @return the EarliestCombAgeSubGrpClr
     */
    public String getEarliestCombAgeSubGrpClr() {
        return (String) getAttributeInternal(EARLIESTCOMBAGESUBGRPCLR);
    }

    /**
     * Gets the attribute value for the calculated attribute LatestCombAgeSubGrpClr.
     * @return the LatestCombAgeSubGrpClr
     */
    public String getLatestCombAgeSubGrpClr() {
        return (String) getAttributeInternal(LATESTCOMBAGESUBGRPCLR);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }


}

