package com.novartis.ecrs.model.view;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Sep 28 00:36:59 IST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CRSVersionLatestNameVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        LatestCrsName {
            protected Object get(CRSVersionLatestNameVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(CRSVersionLatestNameVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LatestCrsVersionStartDate {
            protected Object get(CRSVersionLatestNameVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(CRSVersionLatestNameVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LatestMedVersionDictionary {
            protected Object get(CRSVersionLatestNameVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(CRSVersionLatestNameVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected abstract Object get(CRSVersionLatestNameVORowImpl object);

        protected abstract void put(CRSVersionLatestNameVORowImpl object, Object value);

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int LATESTCRSNAME = AttributesEnum.LatestCrsName.index();
    public static final int LATESTCRSVERSIONSTARTDATE = AttributesEnum.LatestCrsVersionStartDate.index();
    public static final int LATESTMEDVERSIONDICTIONARY = AttributesEnum.LatestMedVersionDictionary.index();

    /**
     * This is the default constructor (do not remove).
     */
    public CRSVersionLatestNameVORowImpl() {
    }
}

