package com.novartis.ecrs.model.view;

import oracle.jbo.domain.Date;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Sep 18 23:29:24 IST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CRSVersionComparePendingVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public CRSVersionComparePendingVOImpl() {
    }

    /**
     * Returns the bind variable value for bindCrsId.
     * @return bind variable value for bindCrsId
     */
    public Integer getbindCrsId() {
        return (Integer) getNamedWhereClauseParam("bindCrsId");
    }

    /**
     * Sets <code>value</code> for bind variable bindCrsId.
     * @param value value to bind as bindCrsId
     */
    public void setbindCrsId(Integer value) {
        setNamedWhereClauseParam("bindCrsId", value);
    }

    /**
     * Returns the bind variable value for bindUserId.
     * @return bind variable value for bindUserId
     */
    public String getbindUserId() {
        return (String) getNamedWhereClauseParam("bindUserId");
    }

    /**
     * Sets <code>value</code> for bind variable bindUserId.
     * @param value value to bind as bindUserId
     */
    public void setbindUserId(String value) {
        setNamedWhereClauseParam("bindUserId", value);
    }


}

