package com.novartis.ecrs.model.view;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Sep 28 00:28:05 IST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CRSVersionEarlierstNameVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        EarliestCrsName {
            protected Object get(CRSVersionEarlierstNameVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(CRSVersionEarlierstNameVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EarliestCrsVersionStrtDate {
            protected Object get(CRSVersionEarlierstNameVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(CRSVersionEarlierstNameVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EarliestMeddraVersionDict {
            protected Object get(CRSVersionEarlierstNameVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(CRSVersionEarlierstNameVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected abstract Object get(CRSVersionEarlierstNameVORowImpl object);

        protected abstract void put(CRSVersionEarlierstNameVORowImpl object, Object value);

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int EARLIESTCRSNAME = AttributesEnum.EarliestCrsName.index();
    public static final int EARLIESTCRSVERSIONSTRTDATE = AttributesEnum.EarliestCrsVersionStrtDate.index();
    public static final int EARLIESTMEDDRAVERSIONDICT = AttributesEnum.EarliestMeddraVersionDict.index();

    /**
     * This is the default constructor (do not remove).
     */
    public CRSVersionEarlierstNameVORowImpl() {
    }
}

