package com.novartis.ecrs.model.view;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Jul 04 23:19:52 IST 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ValidateRiskRelationDefVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public ValidateRiskRelationDefVOImpl() {
    }
}

