package com.novartis.ecrs.model.view;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Jul 22 23:44:41 IST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class VersionsVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public VersionsVOImpl() {
    }

    /**
     * Returns the variable value for bindCrsId.
     * @return variable value for bindCrsId
     */
    public Long getbindCrsId() {
        return (Long) ensureVariableManager().getVariableValue("bindCrsId");
    }

    /**
     * Sets <code>value</code> for variable bindCrsId.
     * @param value value to bind as bindCrsId
     */
    public void setbindCrsId(Long value) {
        ensureVariableManager().setVariableValue("bindCrsId", value);
    }
}

