package com.novartis.ecrs.model.view.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Aug 19 14:07:35 IST 2016
// ---------------------------------------------------------------------
public interface CrsRiskDefinitionsVO extends ViewObject {
    void undoDelete();
}
