package com.novartis.ecrs.model.view.riskdefs;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Jun 15 17:35:14 IST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MedDraDefinitionExitsVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public MedDraDefinitionExitsVOImpl() {
    }

    /**
     * Returns the bind variable value for bindCrsId.
     * @return bind variable value for bindCrsId
     */
    public String getbindCrsId() {
        return (String) getNamedWhereClauseParam("bindCrsId");
    }

    /**
     * Sets <code>value</code> for bind variable bindCrsId.
     * @param value value to bind as bindCrsId
     */
    public void setbindCrsId(String value) {
        setNamedWhereClauseParam("bindCrsId", value);
    }

    /**
     * Returns the bind variable value for bindSafetyTopic.
     * @return bind variable value for bindSafetyTopic
     */
    public String getbindSafetyTopic() {
        return (String) getNamedWhereClauseParam("bindSafetyTopic");
    }

    /**
     * Sets <code>value</code> for bind variable bindSafetyTopic.
     * @param value value to bind as bindSafetyTopic
     */
    public void setbindSafetyTopic(String value) {
        setNamedWhereClauseParam("bindSafetyTopic", value);
    }
}

